// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | (string & {});
};

export type UserAuthResponse = {
    token?: string;
    user?: UserUserResponse;
};

export type UserErrorResponse = {
    error?: string;
};

export type UserLoginInput = {
    email: string;
    password: string;
};

export type UserMessageResponse = {
    message?: string;
};

export type UserRegisterInput = {
    confirm_password: string;
    email: string;
    name: string;
    password: string;
    role: 'student' | 'teacher';
};

export type UserUserResponse = {
    email?: string;
    id?: number;
    name?: string;
    role?: string;
};

export type PostLoginData = {
    /**
     * Data login
     */
    body: UserLoginInput;
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginErrors = {
    /**
     * Unauthorized
     */
    401: UserErrorResponse;
};

export type PostLoginError = PostLoginErrors[keyof PostLoginErrors];

export type PostLoginResponses = {
    /**
     * OK
     */
    200: UserAuthResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
};

export type PostLogoutError = PostLogoutErrors[keyof PostLogoutErrors];

export type PostLogoutResponses = {
    /**
     * OK
     */
    200: UserMessageResponse;
};

export type PostLogoutResponse = PostLogoutResponses[keyof PostLogoutResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetMeErrors = {
    /**
     * Unauthorized
     */
    401: UserErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: UserUserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type PostRegisterData = {
    /**
     * Data registrasi
     */
    body: UserRegisterInput;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
    /**
     * Internal Server Error
     */
    500: UserErrorResponse;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    /**
     * Created
     */
    201: UserAuthResponse;
};

export type PostRegisterResponse = PostRegisterResponses[keyof PostRegisterResponses];
