// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | (string & {});
};

export type AnswerAnswerResponse = {
    content?: string;
    created_at?: string;
    id?: number;
    is_owner?: boolean;
    plain_content?: string;
    user_avatar?: string;
    user_name?: string;
};

export type AnswerCreateAnswerInput = {
    content?: string;
};

export type AnswerErrorResponse = {
    error?: string;
};

export type AnswerMessageResponse = {
    message?: string;
};

export type ChapterChapterResponse = {
    class_id?: number;
    class_name?: string;
    cover_url?: string;
    description?: string;
    id?: number;
    material_count?: number;
    order?: number;
    slug?: string;
    subject_id?: number;
    subject_name?: string;
    title?: string;
};

export type ChapterCreateInput = {
    class_id?: number;
    cover_url?: string;
    description?: string;
    order?: number;
    subject_id?: number;
    title?: string;
};

export type ChapterErrorResponse = {
    error?: string;
};

export type ChapterMessageResponse = {
    message?: string;
};

export type ChapterUpdateInput = {
    cover_url?: string;
    description?: string;
    order?: number;
    title?: string;
};

export type ClassClassResponse = {
    id?: number;
    name?: string;
    slug?: string;
};

export type ClassErrorResponse = {
    error?: string;
};

export type ClassMessageResponse = {
    message?: string;
};

export type ForumCreateQuestionInput = {
    content?: string;
    subject_id?: number;
};

export type ForumErrorResponse = {
    error?: string;
};

export type ForumMessageResponse = {
    message?: string;
};

export type ForumQuestionResponse = {
    content?: string;
    created_at?: string;
    id?: number;
    is_owner?: boolean;
    plain_content?: string;
    status?: string;
    subject_id?: number;
    subject_name?: string;
    user_avatar?: string;
    user_name?: string;
};

export type GalleryGalleryDeleteResponse = {
    message?: string;
};

export type GalleryGalleryErrorResponse = {
    error?: string;
};

export type GalleryGalleryImageResponse = {
    created_at?: string;
    id?: number;
    is_owner?: boolean;
    original_name?: string;
    title?: string;
    url?: string;
};

export type InvoiceErrorResponse = {
    error?: string;
};

export type InvoiceInvoiceResponse = {
    amount?: number;
    created_at?: string;
    end_date?: string;
    id?: number;
    note?: string;
    start_date?: string;
    status?: string;
    user_id?: number;
    user_name?: string;
};

export type InvoiceMessageResponse = {
    message?: string;
};

export type MaterialCreateInput = {
    chapter_id?: number;
    content?: string;
    description?: string;
    order?: number;
    status?: string;
    title?: string;
    type?: string;
    video_url?: string;
};

export type MaterialErrorResponse = {
    error?: string;
};

export type MaterialMaterialResponse = {
    chapter_id?: number;
    chapter_name?: string;
    content?: string;
    description?: string;
    id?: number;
    order?: number;
    slug?: string;
    status?: string;
    title?: string;
    type?: string;
    video_url?: string;
};

export type MaterialMessageResponse = {
    message?: string;
};

export type MaterialUpdateInput = {
    chapter_id?: number;
    content?: string;
    description?: string;
    order?: number;
    status?: string;
    title?: string;
    type?: string;
    video_url?: string;
};

export type PushErrorResponse = {
    error?: string;
};

export type PushMessageResponse = {
    message?: string;
};

export type PushSubscribeInput = {
    endpoint?: string;
    keys?: {
        auth?: string;
        p256dh?: string;
    };
};

export type QuestionbankAnswerResponse = {
    content?: string;
    id?: number;
    is_correct?: boolean;
};

export type QuestionbankBulkDeleteFailedItem = {
    error?: string;
    id?: number;
};

export type QuestionbankBulkDeleteResult = {
    deleted?: Array<number>;
    failed?: Array<QuestionbankBulkDeleteFailedItem>;
};

export type QuestionbankCreateInput = {
    answers?: Array<QuestionbankQuestionbankAnswerInput>;
    chapter_id?: number;
    explanation?: string;
    question?: string;
    user_id?: number;
};

export type QuestionbankErrorResponse = {
    error?: string;
};

export type QuestionbankPaginatedResponse = {
    data?: Array<QuestionbankQuestionResponse>;
    meta?: QuestionbankPaginationMeta;
};

export type QuestionbankPaginationMeta = {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type QuestionbankQuestionResponse = {
    answers?: Array<QuestionbankAnswerResponse>;
    chapter_id?: number;
    chapter_title?: string;
    created_at?: string;
    explanation?: string;
    id?: number;
    question?: string;
    user_id?: number;
    user_name?: string;
};

export type QuestionbankQuestionbankAnswerInput = {
    content?: string;
    is_correct?: boolean;
};

export type QuestionbankUpdateInput = {
    answers?: Array<QuestionbankQuestionbankAnswerInput>;
    chapter_id?: number;
    explanation?: string;
    question?: string;
};

export type QuestionpackageCreateInput = {
    description?: string;
    name?: string;
    question_ids?: Array<number>;
};

export type QuestionpackageErrorResponse = {
    error?: string;
};

export type QuestionpackageMessageResponse = {
    message?: string;
};

export type QuestionpackagePackageQuestionResponse = {
    id?: number;
    question?: string;
};

export type QuestionpackagePackageResponse = {
    created_at?: string;
    description?: string;
    id?: number;
    name?: string;
    questions?: Array<QuestionpackagePackageQuestionResponse>;
};

export type QuestionpackageUpdateInput = {
    description?: string;
    name?: string;
    question_ids?: Array<number>;
};

export type SubjectCreateInput = {
    class_ids?: Array<number>;
    name?: string;
};

export type SubjectErrorResponse = {
    error?: string;
};

export type SubjectMessageResponse = {
    message?: string;
};

export type SubjectSubjectResponse = {
    class_ids?: Array<number>;
    id?: number;
    material_count?: number;
    name?: string;
    slug?: string;
};

export type SubjectUpdateInput = {
    class_ids?: Array<number>;
    name?: string;
};

export type TutoringAvailabilityResponse = {
    day_of_week?: number;
    end_time?: string;
    id?: number;
    start_time?: string;
    teacher_id?: number;
};

export type TutoringBookingResponse = {
    created_at?: string;
    date?: string;
    end_time?: string;
    id?: number;
    note?: string;
    start_time?: string;
    status?: string;
    student_id?: number;
    student_name?: string;
    teacher_id?: number;
    teacher_name?: string;
};

export type TutoringCreateAvailabilityInput = {
    day_of_week?: number;
    end_time?: string;
    start_time?: string;
};

export type TutoringCreateBookingInput = {
    date?: string;
    end_time?: string;
    note?: string;
    start_time?: string;
    teacher_id?: number;
};

export type TutoringErrorResponse = {
    error?: string;
};

export type TutoringMessageResponse = {
    message?: string;
};

export type TutoringSubjectInfo = {
    id?: number;
    name?: string;
};

export type TutoringTeacherResponse = {
    avatar_url?: string;
    email?: string;
    id?: number;
    name?: string;
    subjects?: Array<TutoringSubjectInfo>;
};

export type UploadUploadResponse = {
    file_name?: string;
    id?: number;
    url?: string;
};

export type UserAdminUserResponse = {
    avatar_url?: string;
    created_at?: string;
    email?: string;
    id?: number;
    name?: string;
    payment_status?: string;
    roles?: Array<string>;
    subjects?: Array<UserSubjectInfo>;
};

export type UserErrorResponse = {
    error?: string;
};

export type UserMessageResponse = {
    message?: string;
};

export type UserSubjectInfo = {
    id?: number;
    name?: string;
};

export type UserUpdateRoleRequest = {
    roles?: Array<string>;
};

export type UserUserResponse = {
    avatar_url?: string;
    class_id?: number;
    email?: string;
    id?: number;
    name?: string;
    payment_status?: string;
    roles?: Array<string>;
    subjects?: Array<UserSubjectInfo>;
};

export type GetAdminChaptersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by class ID
         */
        class_id?: number;
        /**
         * Filter by subject ID
         */
        subject_id?: number;
    };
    url: '/admin/chapters';
};

export type GetAdminChaptersResponses = {
    /**
     * OK
     */
    200: Array<ChapterChapterResponse>;
};

export type GetAdminChaptersResponse = GetAdminChaptersResponses[keyof GetAdminChaptersResponses];

export type PostAdminChaptersData = {
    /**
     * Data chapter
     */
    body: ChapterCreateInput;
    path?: never;
    query?: never;
    url: '/admin/chapters';
};

export type PostAdminChaptersErrors = {
    /**
     * Bad Request
     */
    400: ChapterErrorResponse;
};

export type PostAdminChaptersError = PostAdminChaptersErrors[keyof PostAdminChaptersErrors];

export type PostAdminChaptersResponses = {
    /**
     * Created
     */
    201: ChapterChapterResponse;
};

export type PostAdminChaptersResponse = PostAdminChaptersResponses[keyof PostAdminChaptersResponses];

export type DeleteAdminChaptersByIdData = {
    body?: never;
    path: {
        /**
         * Chapter ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/chapters/{id}';
};

export type DeleteAdminChaptersByIdResponses = {
    /**
     * OK
     */
    200: ChapterMessageResponse;
};

export type DeleteAdminChaptersByIdResponse = DeleteAdminChaptersByIdResponses[keyof DeleteAdminChaptersByIdResponses];

export type PatchAdminChaptersByIdData = {
    /**
     * Data update
     */
    body: ChapterUpdateInput;
    path: {
        /**
         * Chapter ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/chapters/{id}';
};

export type PatchAdminChaptersByIdErrors = {
    /**
     * Bad Request
     */
    400: ChapterErrorResponse;
};

export type PatchAdminChaptersByIdError = PatchAdminChaptersByIdErrors[keyof PatchAdminChaptersByIdErrors];

export type PatchAdminChaptersByIdResponses = {
    /**
     * OK
     */
    200: ChapterChapterResponse;
};

export type PatchAdminChaptersByIdResponse = PatchAdminChaptersByIdResponses[keyof PatchAdminChaptersByIdResponses];

export type PostAdminChaptersByIdCoverData = {
    body: {
        /**
         * File gambar
         */
        image: Blob | File;
    };
    path: {
        /**
         * Chapter ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/chapters/{id}/cover';
};

export type PostAdminChaptersByIdCoverErrors = {
    /**
     * Bad Request
     */
    400: ChapterErrorResponse;
};

export type PostAdminChaptersByIdCoverError = PostAdminChaptersByIdCoverErrors[keyof PostAdminChaptersByIdCoverErrors];

export type PostAdminChaptersByIdCoverResponses = {
    /**
     * OK
     */
    200: ChapterMessageResponse;
};

export type PostAdminChaptersByIdCoverResponse = PostAdminChaptersByIdCoverResponses[keyof PostAdminChaptersByIdCoverResponses];

export type GetAdminClassesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/classes';
};

export type GetAdminClassesResponses = {
    /**
     * OK
     */
    200: Array<ClassClassResponse>;
};

export type GetAdminClassesResponse = GetAdminClassesResponses[keyof GetAdminClassesResponses];

export type PostAdminClassesData = {
    /**
     * Data kelas
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/admin/classes';
};

export type PostAdminClassesErrors = {
    /**
     * Bad Request
     */
    400: ClassErrorResponse;
};

export type PostAdminClassesError = PostAdminClassesErrors[keyof PostAdminClassesErrors];

export type PostAdminClassesResponses = {
    /**
     * Created
     */
    201: ClassClassResponse;
};

export type PostAdminClassesResponse = PostAdminClassesResponses[keyof PostAdminClassesResponses];

export type DeleteAdminClassesByIdData = {
    body?: never;
    path: {
        /**
         * Class ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/classes/{id}';
};

export type DeleteAdminClassesByIdResponses = {
    /**
     * OK
     */
    200: ClassMessageResponse;
};

export type DeleteAdminClassesByIdResponse = DeleteAdminClassesByIdResponses[keyof DeleteAdminClassesByIdResponses];

export type PatchAdminClassesByIdData = {
    /**
     * Data update
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Class ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/classes/{id}';
};

export type PatchAdminClassesByIdErrors = {
    /**
     * Bad Request
     */
    400: ClassErrorResponse;
};

export type PatchAdminClassesByIdError = PatchAdminClassesByIdErrors[keyof PatchAdminClassesByIdErrors];

export type PatchAdminClassesByIdResponses = {
    /**
     * OK
     */
    200: ClassClassResponse;
};

export type PatchAdminClassesByIdResponse = PatchAdminClassesByIdResponses[keyof PatchAdminClassesByIdResponses];

export type GetAdminInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by user ID
         */
        user_id?: number;
        /**
         * Filter by status (paid/pending)
         */
        status?: string;
        /**
         * Search by note, start_date, or end_date
         */
        search?: string;
    };
    url: '/admin/invoices';
};

export type GetAdminInvoicesResponses = {
    /**
     * OK
     */
    200: Array<InvoiceInvoiceResponse>;
};

export type GetAdminInvoicesResponse = GetAdminInvoicesResponses[keyof GetAdminInvoicesResponses];

export type PostAdminInvoicesData = {
    /**
     * Data invoice
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/admin/invoices';
};

export type PostAdminInvoicesErrors = {
    /**
     * Bad Request
     */
    400: InvoiceErrorResponse;
};

export type PostAdminInvoicesError = PostAdminInvoicesErrors[keyof PostAdminInvoicesErrors];

export type PostAdminInvoicesResponses = {
    /**
     * Created
     */
    201: InvoiceInvoiceResponse;
};

export type PostAdminInvoicesResponse = PostAdminInvoicesResponses[keyof PostAdminInvoicesResponses];

export type DeleteAdminInvoicesByIdData = {
    body?: never;
    path: {
        /**
         * Invoice ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/invoices/{id}';
};

export type DeleteAdminInvoicesByIdErrors = {
    /**
     * Bad Request
     */
    400: InvoiceErrorResponse;
};

export type DeleteAdminInvoicesByIdError = DeleteAdminInvoicesByIdErrors[keyof DeleteAdminInvoicesByIdErrors];

export type DeleteAdminInvoicesByIdResponses = {
    /**
     * OK
     */
    200: InvoiceMessageResponse;
};

export type DeleteAdminInvoicesByIdResponse = DeleteAdminInvoicesByIdResponses[keyof DeleteAdminInvoicesByIdResponses];

export type PatchAdminInvoicesByIdToggleData = {
    body?: never;
    path: {
        /**
         * Invoice ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/invoices/{id}/toggle';
};

export type PatchAdminInvoicesByIdToggleErrors = {
    /**
     * Bad Request
     */
    400: InvoiceErrorResponse;
};

export type PatchAdminInvoicesByIdToggleError = PatchAdminInvoicesByIdToggleErrors[keyof PatchAdminInvoicesByIdToggleErrors];

export type PatchAdminInvoicesByIdToggleResponses = {
    /**
     * OK
     */
    200: InvoiceInvoiceResponse;
};

export type PatchAdminInvoicesByIdToggleResponse = PatchAdminInvoicesByIdToggleResponses[keyof PatchAdminInvoicesByIdToggleResponses];

export type GetAdminMaterialsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by chapter ID
         */
        chapter_id?: number;
    };
    url: '/admin/materials';
};

export type GetAdminMaterialsResponses = {
    /**
     * OK
     */
    200: Array<MaterialMaterialResponse>;
};

export type GetAdminMaterialsResponse = GetAdminMaterialsResponses[keyof GetAdminMaterialsResponses];

export type PostAdminMaterialsData = {
    /**
     * Data materi
     */
    body: MaterialCreateInput;
    path?: never;
    query?: never;
    url: '/admin/materials';
};

export type PostAdminMaterialsErrors = {
    /**
     * Bad Request
     */
    400: MaterialErrorResponse;
};

export type PostAdminMaterialsError = PostAdminMaterialsErrors[keyof PostAdminMaterialsErrors];

export type PostAdminMaterialsResponses = {
    /**
     * Created
     */
    201: MaterialMaterialResponse;
};

export type PostAdminMaterialsResponse = PostAdminMaterialsResponses[keyof PostAdminMaterialsResponses];

export type DeleteAdminMaterialsByIdData = {
    body?: never;
    path: {
        /**
         * Material ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/materials/{id}';
};

export type DeleteAdminMaterialsByIdResponses = {
    /**
     * OK
     */
    200: MaterialMessageResponse;
};

export type DeleteAdminMaterialsByIdResponse = DeleteAdminMaterialsByIdResponses[keyof DeleteAdminMaterialsByIdResponses];

export type GetAdminMaterialsByIdData = {
    body?: never;
    path: {
        /**
         * Material ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/materials/{id}';
};

export type GetAdminMaterialsByIdErrors = {
    /**
     * Not Found
     */
    404: MaterialErrorResponse;
};

export type GetAdminMaterialsByIdError = GetAdminMaterialsByIdErrors[keyof GetAdminMaterialsByIdErrors];

export type GetAdminMaterialsByIdResponses = {
    /**
     * OK
     */
    200: MaterialMaterialResponse;
};

export type GetAdminMaterialsByIdResponse = GetAdminMaterialsByIdResponses[keyof GetAdminMaterialsByIdResponses];

export type PatchAdminMaterialsByIdData = {
    /**
     * Data update
     */
    body: MaterialUpdateInput;
    path: {
        /**
         * Material ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/materials/{id}';
};

export type PatchAdminMaterialsByIdErrors = {
    /**
     * Bad Request
     */
    400: MaterialErrorResponse;
};

export type PatchAdminMaterialsByIdError = PatchAdminMaterialsByIdErrors[keyof PatchAdminMaterialsByIdErrors];

export type PatchAdminMaterialsByIdResponses = {
    /**
     * OK
     */
    200: MaterialMaterialResponse;
};

export type PatchAdminMaterialsByIdResponse = PatchAdminMaterialsByIdResponses[keyof PatchAdminMaterialsByIdResponses];

export type GetAdminQuestionPackagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/question-packages';
};

export type GetAdminQuestionPackagesResponses = {
    /**
     * OK
     */
    200: Array<QuestionpackagePackageResponse>;
};

export type GetAdminQuestionPackagesResponse = GetAdminQuestionPackagesResponses[keyof GetAdminQuestionPackagesResponses];

export type PostAdminQuestionPackagesData = {
    /**
     * Data paket
     */
    body: QuestionpackageCreateInput;
    path?: never;
    query?: never;
    url: '/admin/question-packages';
};

export type PostAdminQuestionPackagesErrors = {
    /**
     * Bad Request
     */
    400: QuestionpackageErrorResponse;
};

export type PostAdminQuestionPackagesError = PostAdminQuestionPackagesErrors[keyof PostAdminQuestionPackagesErrors];

export type PostAdminQuestionPackagesResponses = {
    /**
     * Created
     */
    201: QuestionpackagePackageResponse;
};

export type PostAdminQuestionPackagesResponse = PostAdminQuestionPackagesResponses[keyof PostAdminQuestionPackagesResponses];

export type DeleteAdminQuestionPackagesByIdData = {
    body?: never;
    path: {
        /**
         * Package ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/question-packages/{id}';
};

export type DeleteAdminQuestionPackagesByIdErrors = {
    /**
     * Not Found
     */
    404: QuestionpackageErrorResponse;
};

export type DeleteAdminQuestionPackagesByIdError = DeleteAdminQuestionPackagesByIdErrors[keyof DeleteAdminQuestionPackagesByIdErrors];

export type DeleteAdminQuestionPackagesByIdResponses = {
    /**
     * OK
     */
    200: QuestionpackageMessageResponse;
};

export type DeleteAdminQuestionPackagesByIdResponse = DeleteAdminQuestionPackagesByIdResponses[keyof DeleteAdminQuestionPackagesByIdResponses];

export type GetAdminQuestionPackagesByIdData = {
    body?: never;
    path: {
        /**
         * Package ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/question-packages/{id}';
};

export type GetAdminQuestionPackagesByIdErrors = {
    /**
     * Not Found
     */
    404: QuestionpackageErrorResponse;
};

export type GetAdminQuestionPackagesByIdError = GetAdminQuestionPackagesByIdErrors[keyof GetAdminQuestionPackagesByIdErrors];

export type GetAdminQuestionPackagesByIdResponses = {
    /**
     * OK
     */
    200: QuestionpackagePackageResponse;
};

export type GetAdminQuestionPackagesByIdResponse = GetAdminQuestionPackagesByIdResponses[keyof GetAdminQuestionPackagesByIdResponses];

export type PatchAdminQuestionPackagesByIdData = {
    /**
     * Data update
     */
    body: QuestionpackageUpdateInput;
    path: {
        /**
         * Package ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/question-packages/{id}';
};

export type PatchAdminQuestionPackagesByIdErrors = {
    /**
     * Bad Request
     */
    400: QuestionpackageErrorResponse;
};

export type PatchAdminQuestionPackagesByIdError = PatchAdminQuestionPackagesByIdErrors[keyof PatchAdminQuestionPackagesByIdErrors];

export type PatchAdminQuestionPackagesByIdResponses = {
    /**
     * OK
     */
    200: QuestionpackagePackageResponse;
};

export type PatchAdminQuestionPackagesByIdResponse = PatchAdminQuestionPackagesByIdResponses[keyof PatchAdminQuestionPackagesByIdResponses];

export type GetAdminQuestionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/questions';
};

export type GetAdminQuestionsErrors = {
    /**
     * Bad Request
     */
    400: ForumErrorResponse;
};

export type GetAdminQuestionsError = GetAdminQuestionsErrors[keyof GetAdminQuestionsErrors];

export type GetAdminQuestionsResponses = {
    /**
     * OK
     */
    200: Array<ForumQuestionResponse>;
};

export type GetAdminQuestionsResponse = GetAdminQuestionsResponses[keyof GetAdminQuestionsResponses];

export type DeleteAdminQuestionsBankData = {
    /**
     * Daftar ID soal yang akan dihapus
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/admin/questions-bank';
};

export type DeleteAdminQuestionsBankResponses = {
    /**
     * OK
     */
    200: QuestionbankBulkDeleteResult;
};

export type DeleteAdminQuestionsBankResponse = DeleteAdminQuestionsBankResponses[keyof DeleteAdminQuestionsBankResponses];

export type GetAdminQuestionsBankData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by chapter ID
         */
        chapter_id?: number;
        /**
         * Filter by creator user ID
         */
        created_by?: number;
    };
    url: '/admin/questions-bank';
};

export type GetAdminQuestionsBankResponses = {
    /**
     * OK
     */
    200: Array<QuestionbankQuestionResponse>;
};

export type GetAdminQuestionsBankResponse = GetAdminQuestionsBankResponses[keyof GetAdminQuestionsBankResponses];

export type PostAdminQuestionsBankData = {
    /**
     * Data soal
     */
    body: QuestionbankCreateInput;
    path?: never;
    query?: never;
    url: '/admin/questions-bank';
};

export type PostAdminQuestionsBankErrors = {
    /**
     * Bad Request
     */
    400: QuestionbankErrorResponse;
};

export type PostAdminQuestionsBankError = PostAdminQuestionsBankErrors[keyof PostAdminQuestionsBankErrors];

export type PostAdminQuestionsBankResponses = {
    /**
     * Created
     */
    201: QuestionbankQuestionResponse;
};

export type PostAdminQuestionsBankResponse = PostAdminQuestionsBankResponses[keyof PostAdminQuestionsBankResponses];

export type GetAdminQuestionsBankPaginatedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by chapter ID
         */
        chapter_id?: number;
        /**
         * Page number (default 1)
         */
        page?: number;
        /**
         * Items per page (default 10)
         */
        per_page?: number;
    };
    url: '/admin/questions-bank/paginated';
};

export type GetAdminQuestionsBankPaginatedResponses = {
    /**
     * OK
     */
    200: QuestionbankPaginatedResponse;
};

export type GetAdminQuestionsBankPaginatedResponse = GetAdminQuestionsBankPaginatedResponses[keyof GetAdminQuestionsBankPaginatedResponses];

export type PatchAdminQuestionsBankByIdData = {
    /**
     * Data update
     */
    body: QuestionbankUpdateInput;
    path: {
        /**
         * Question ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/questions-bank/{id}';
};

export type PatchAdminQuestionsBankByIdErrors = {
    /**
     * Bad Request
     */
    400: QuestionbankErrorResponse;
};

export type PatchAdminQuestionsBankByIdError = PatchAdminQuestionsBankByIdErrors[keyof PatchAdminQuestionsBankByIdErrors];

export type PatchAdminQuestionsBankByIdResponses = {
    /**
     * OK
     */
    200: QuestionbankQuestionResponse;
};

export type PatchAdminQuestionsBankByIdResponse = PatchAdminQuestionsBankByIdResponses[keyof PatchAdminQuestionsBankByIdResponses];

export type DeleteAdminQuestionsByIdData = {
    body?: never;
    path: {
        /**
         * Question ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/questions/{id}';
};

export type DeleteAdminQuestionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ForumErrorResponse;
};

export type DeleteAdminQuestionsByIdError = DeleteAdminQuestionsByIdErrors[keyof DeleteAdminQuestionsByIdErrors];

export type DeleteAdminQuestionsByIdResponses = {
    /**
     * OK
     */
    200: Array<ForumQuestionResponse>;
};

export type DeleteAdminQuestionsByIdResponse = DeleteAdminQuestionsByIdResponses[keyof DeleteAdminQuestionsByIdResponses];

export type PostAdminSubjectsData = {
    /**
     * Data subject
     */
    body: SubjectCreateInput;
    path?: never;
    query?: never;
    url: '/admin/subjects';
};

export type PostAdminSubjectsErrors = {
    /**
     * Bad Request
     */
    400: SubjectErrorResponse;
};

export type PostAdminSubjectsError = PostAdminSubjectsErrors[keyof PostAdminSubjectsErrors];

export type PostAdminSubjectsResponses = {
    /**
     * Created
     */
    201: SubjectSubjectResponse;
};

export type PostAdminSubjectsResponse = PostAdminSubjectsResponses[keyof PostAdminSubjectsResponses];

export type DeleteAdminSubjectsByIdData = {
    body?: never;
    path: {
        /**
         * Subject ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/subjects/{id}';
};

export type DeleteAdminSubjectsByIdResponses = {
    /**
     * OK
     */
    200: SubjectMessageResponse;
};

export type DeleteAdminSubjectsByIdResponse = DeleteAdminSubjectsByIdResponses[keyof DeleteAdminSubjectsByIdResponses];

export type PatchAdminSubjectsByIdData = {
    /**
     * Data update
     */
    body: SubjectUpdateInput;
    path: {
        /**
         * Subject ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/subjects/{id}';
};

export type PatchAdminSubjectsByIdErrors = {
    /**
     * Bad Request
     */
    400: SubjectErrorResponse;
};

export type PatchAdminSubjectsByIdError = PatchAdminSubjectsByIdErrors[keyof PatchAdminSubjectsByIdErrors];

export type PatchAdminSubjectsByIdResponses = {
    /**
     * OK
     */
    200: SubjectSubjectResponse;
};

export type PatchAdminSubjectsByIdResponse = PatchAdminSubjectsByIdResponses[keyof PatchAdminSubjectsByIdResponses];

export type GetAdminSubjectsBySubjectIdImagesData = {
    body?: never;
    path: {
        /**
         * Subject ID
         */
        subject_id: number;
    };
    query?: {
        /**
         * Filter by title
         */
        q?: string;
    };
    url: '/admin/subjects/{subject_id}/images';
};

export type GetAdminSubjectsBySubjectIdImagesResponses = {
    /**
     * OK
     */
    200: Array<GalleryGalleryImageResponse>;
};

export type GetAdminSubjectsBySubjectIdImagesResponse = GetAdminSubjectsBySubjectIdImagesResponses[keyof GetAdminSubjectsBySubjectIdImagesResponses];

export type PostAdminSubjectsBySubjectIdImagesData = {
    body: {
        /**
         * File gambar
         */
        image: Blob | File;
        /**
         * Judul gambar
         */
        title?: string;
    };
    path: {
        /**
         * Subject ID
         */
        subject_id: number;
    };
    query?: never;
    url: '/admin/subjects/{subject_id}/images';
};

export type PostAdminSubjectsBySubjectIdImagesErrors = {
    /**
     * Bad Request
     */
    400: GalleryGalleryErrorResponse;
};

export type PostAdminSubjectsBySubjectIdImagesError = PostAdminSubjectsBySubjectIdImagesErrors[keyof PostAdminSubjectsBySubjectIdImagesErrors];

export type PostAdminSubjectsBySubjectIdImagesResponses = {
    /**
     * Created
     */
    201: GalleryGalleryImageResponse;
};

export type PostAdminSubjectsBySubjectIdImagesResponse = PostAdminSubjectsBySubjectIdImagesResponses[keyof PostAdminSubjectsBySubjectIdImagesResponses];

export type DeleteAdminSubjectsBySubjectIdImagesByIdData = {
    body?: never;
    path: {
        /**
         * Subject ID
         */
        subject_id: number;
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/subjects/{subject_id}/images/{id}';
};

export type DeleteAdminSubjectsBySubjectIdImagesByIdErrors = {
    /**
     * Forbidden
     */
    403: GalleryGalleryErrorResponse;
    /**
     * Not Found
     */
    404: GalleryGalleryErrorResponse;
};

export type DeleteAdminSubjectsBySubjectIdImagesByIdError = DeleteAdminSubjectsBySubjectIdImagesByIdErrors[keyof DeleteAdminSubjectsBySubjectIdImagesByIdErrors];

export type DeleteAdminSubjectsBySubjectIdImagesByIdResponses = {
    /**
     * OK
     */
    200: GalleryGalleryDeleteResponse;
};

export type DeleteAdminSubjectsBySubjectIdImagesByIdResponse = DeleteAdminSubjectsBySubjectIdImagesByIdResponses[keyof DeleteAdminSubjectsBySubjectIdImagesByIdResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by name or email
         */
        search?: string;
        /**
         * Filter by role (student/teacher/admin)
         */
        role?: string;
    };
    url: '/admin/users';
};

export type GetAdminUsersErrors = {
    /**
     * Internal Server Error
     */
    500: UserErrorResponse;
};

export type GetAdminUsersError = GetAdminUsersErrors[keyof GetAdminUsersErrors];

export type GetAdminUsersResponses = {
    /**
     * OK
     */
    200: Array<UserAdminUserResponse>;
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type DeleteAdminUsersByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type DeleteAdminUsersByIdErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
    /**
     * Internal Server Error
     */
    500: UserErrorResponse;
};

export type DeleteAdminUsersByIdError = DeleteAdminUsersByIdErrors[keyof DeleteAdminUsersByIdErrors];

export type DeleteAdminUsersByIdResponses = {
    /**
     * OK
     */
    200: UserMessageResponse;
};

export type DeleteAdminUsersByIdResponse = DeleteAdminUsersByIdResponses[keyof DeleteAdminUsersByIdResponses];

export type PatchAdminUsersByIdPaymentData = {
    /**
     * Status
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}/payment';
};

export type PatchAdminUsersByIdPaymentErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
};

export type PatchAdminUsersByIdPaymentError = PatchAdminUsersByIdPaymentErrors[keyof PatchAdminUsersByIdPaymentErrors];

export type PatchAdminUsersByIdPaymentResponses = {
    /**
     * OK
     */
    200: UserMessageResponse;
};

export type PatchAdminUsersByIdPaymentResponse = PatchAdminUsersByIdPaymentResponses[keyof PatchAdminUsersByIdPaymentResponses];

export type PatchAdminUsersByIdRoleData = {
    /**
     * Role baru
     */
    body: UserUpdateRoleRequest;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}/role';
};

export type PatchAdminUsersByIdRoleErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
    /**
     * Internal Server Error
     */
    500: UserErrorResponse;
};

export type PatchAdminUsersByIdRoleError = PatchAdminUsersByIdRoleErrors[keyof PatchAdminUsersByIdRoleErrors];

export type PatchAdminUsersByIdRoleResponses = {
    /**
     * OK
     */
    200: UserMessageResponse;
};

export type PatchAdminUsersByIdRoleResponse = PatchAdminUsersByIdRoleResponses[keyof PatchAdminUsersByIdRoleResponses];

export type PatchAdminUsersByIdSubjectsData = {
    /**
     * Daftar subject_ids
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}/subjects';
};

export type PatchAdminUsersByIdSubjectsErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
    /**
     * Internal Server Error
     */
    500: UserErrorResponse;
};

export type PatchAdminUsersByIdSubjectsError = PatchAdminUsersByIdSubjectsErrors[keyof PatchAdminUsersByIdSubjectsErrors];

export type PatchAdminUsersByIdSubjectsResponses = {
    /**
     * OK
     */
    200: UserAdminUserResponse;
};

export type PatchAdminUsersByIdSubjectsResponse = PatchAdminUsersByIdSubjectsResponses[keyof PatchAdminUsersByIdSubjectsResponses];

export type GetAuthGoogleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type GetAuthGoogleCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google/callback';
};

export type GetChaptersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by class ID
         */
        class_id?: number;
        /**
         * Filter by subject ID
         */
        subject_id?: number;
    };
    url: '/chapters';
};

export type GetChaptersResponses = {
    /**
     * OK
     */
    200: Array<ChapterChapterResponse>;
};

export type GetChaptersResponse = GetChaptersResponses[keyof GetChaptersResponses];

export type GetClassesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/classes';
};

export type GetClassesResponses = {
    /**
     * OK
     */
    200: Array<ClassClassResponse>;
};

export type GetClassesResponse = GetClassesResponses[keyof GetClassesResponses];

export type GetInvoicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/invoices';
};

export type GetInvoicesResponses = {
    /**
     * OK
     */
    200: Array<InvoiceInvoiceResponse>;
};

export type GetInvoicesResponse = GetInvoicesResponses[keyof GetInvoicesResponses];

export type PostLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
};

export type PostLogoutError = PostLogoutErrors[keyof PostLogoutErrors];

export type PostLogoutResponses = {
    /**
     * OK
     */
    200: UserMessageResponse;
};

export type PostLogoutResponse = PostLogoutResponses[keyof PostLogoutResponses];

export type GetMaterialsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by chapter ID
         */
        chapter_id?: number;
    };
    url: '/materials';
};

export type GetMaterialsResponses = {
    /**
     * OK
     */
    200: Array<MaterialMaterialResponse>;
};

export type GetMaterialsResponse = GetMaterialsResponses[keyof GetMaterialsResponses];

export type GetMaterialsByIdData = {
    body?: never;
    path: {
        /**
         * Material ID
         */
        id: number;
    };
    query?: never;
    url: '/materials/{id}';
};

export type GetMaterialsByIdErrors = {
    /**
     * Not Found
     */
    404: MaterialErrorResponse;
};

export type GetMaterialsByIdError = GetMaterialsByIdErrors[keyof GetMaterialsByIdErrors];

export type GetMaterialsByIdResponses = {
    /**
     * OK
     */
    200: MaterialMaterialResponse;
};

export type GetMaterialsByIdResponse = GetMaterialsByIdResponses[keyof GetMaterialsByIdResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetMeErrors = {
    /**
     * Unauthorized
     */
    401: UserErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: UserUserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type PatchMeData = {
    /**
     * Data profile
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/me';
};

export type PatchMeErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
};

export type PatchMeError = PatchMeErrors[keyof PatchMeErrors];

export type PatchMeResponses = {
    /**
     * OK
     */
    200: UserUserResponse;
};

export type PatchMeResponse = PatchMeResponses[keyof PatchMeResponses];

export type GetPushPublicKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/push/public-key';
};

export type GetPushPublicKeyResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetPushPublicKeyResponse = GetPushPublicKeyResponses[keyof GetPushPublicKeyResponses];

export type PostPushSubscribeData = {
    /**
     * Subscription data
     */
    body: PushSubscribeInput;
    path?: never;
    query?: never;
    url: '/push/subscribe';
};

export type PostPushSubscribeErrors = {
    /**
     * Bad Request
     */
    400: PushErrorResponse;
};

export type PostPushSubscribeError = PostPushSubscribeErrors[keyof PostPushSubscribeErrors];

export type PostPushSubscribeResponses = {
    /**
     * OK
     */
    200: PushMessageResponse;
};

export type PostPushSubscribeResponse = PostPushSubscribeResponses[keyof PostPushSubscribeResponses];

export type GetQuestionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by subject
         */
        subject_id?: number;
        /**
         * Filter by current user
         */
        mine?: boolean;
        /**
         * Filter unanswered only
         */
        unanswered?: boolean;
    };
    url: '/questions';
};

export type GetQuestionsResponses = {
    /**
     * OK
     */
    200: Array<ForumQuestionResponse>;
};

export type GetQuestionsResponse = GetQuestionsResponses[keyof GetQuestionsResponses];

export type PostQuestionsData = {
    /**
     * Data pertanyaan
     */
    body: ForumCreateQuestionInput;
    path?: never;
    query?: never;
    url: '/questions';
};

export type PostQuestionsErrors = {
    /**
     * Bad Request
     */
    400: ForumErrorResponse;
};

export type PostQuestionsError = PostQuestionsErrors[keyof PostQuestionsErrors];

export type PostQuestionsResponses = {
    /**
     * Created
     */
    201: ForumQuestionResponse;
};

export type PostQuestionsResponse = PostQuestionsResponses[keyof PostQuestionsResponses];

export type DeleteQuestionsByIdData = {
    body?: never;
    path: {
        /**
         * Question ID
         */
        id: number;
    };
    query?: never;
    url: '/questions/{id}';
};

export type DeleteQuestionsByIdResponses = {
    /**
     * OK
     */
    200: ForumMessageResponse;
};

export type DeleteQuestionsByIdResponse = DeleteQuestionsByIdResponses[keyof DeleteQuestionsByIdResponses];

export type GetQuestionsByIdData = {
    body?: never;
    path: {
        /**
         * Question ID
         */
        id: number;
    };
    query?: never;
    url: '/questions/{id}';
};

export type GetQuestionsByIdErrors = {
    /**
     * Not Found
     */
    404: ForumErrorResponse;
};

export type GetQuestionsByIdError = GetQuestionsByIdErrors[keyof GetQuestionsByIdErrors];

export type GetQuestionsByIdResponses = {
    /**
     * OK
     */
    200: ForumQuestionResponse;
};

export type GetQuestionsByIdResponse = GetQuestionsByIdResponses[keyof GetQuestionsByIdResponses];

export type GetQuestionsByQuestionIdAnswersData = {
    body?: never;
    path: {
        /**
         * Question ID
         */
        question_id: number;
    };
    query?: never;
    url: '/questions/{question_id}/answers';
};

export type GetQuestionsByQuestionIdAnswersResponses = {
    /**
     * OK
     */
    200: Array<AnswerAnswerResponse>;
};

export type GetQuestionsByQuestionIdAnswersResponse = GetQuestionsByQuestionIdAnswersResponses[keyof GetQuestionsByQuestionIdAnswersResponses];

export type PostQuestionsByQuestionIdAnswersData = {
    /**
     * Data jawaban
     */
    body: AnswerCreateAnswerInput;
    path: {
        /**
         * Question ID
         */
        question_id: number;
    };
    query?: never;
    url: '/questions/{question_id}/answers';
};

export type PostQuestionsByQuestionIdAnswersErrors = {
    /**
     * Bad Request
     */
    400: AnswerErrorResponse;
};

export type PostQuestionsByQuestionIdAnswersError = PostQuestionsByQuestionIdAnswersErrors[keyof PostQuestionsByQuestionIdAnswersErrors];

export type PostQuestionsByQuestionIdAnswersResponses = {
    /**
     * Created
     */
    201: AnswerAnswerResponse;
};

export type PostQuestionsByQuestionIdAnswersResponse = PostQuestionsByQuestionIdAnswersResponses[keyof PostQuestionsByQuestionIdAnswersResponses];

export type DeleteQuestionsByQuestionIdAnswersByIdData = {
    body?: never;
    path: {
        /**
         * Question ID
         */
        question_id: number;
        /**
         * Answer ID
         */
        id: number;
    };
    query?: never;
    url: '/questions/{question_id}/answers/{id}';
};

export type DeleteQuestionsByQuestionIdAnswersByIdErrors = {
    /**
     * Bad Request
     */
    400: AnswerErrorResponse;
};

export type DeleteQuestionsByQuestionIdAnswersByIdError = DeleteQuestionsByQuestionIdAnswersByIdErrors[keyof DeleteQuestionsByQuestionIdAnswersByIdErrors];

export type DeleteQuestionsByQuestionIdAnswersByIdResponses = {
    /**
     * OK
     */
    200: AnswerMessageResponse;
};

export type DeleteQuestionsByQuestionIdAnswersByIdResponse = DeleteQuestionsByQuestionIdAnswersByIdResponses[keyof DeleteQuestionsByQuestionIdAnswersByIdResponses];

export type GetQuestionsByQuestionIdImagesData = {
    body?: never;
    path: {
        /**
         * Question ID
         */
        question_id: number;
    };
    query?: never;
    url: '/questions/{question_id}/images';
};

export type GetQuestionsByQuestionIdImagesResponses = {
    /**
     * OK
     */
    200: Array<UploadUploadResponse>;
};

export type GetQuestionsByQuestionIdImagesResponse = GetQuestionsByQuestionIdImagesResponses[keyof GetQuestionsByQuestionIdImagesResponses];

export type PostQuestionsByQuestionIdImagesData = {
    body: {
        /**
         * File gambar
         */
        image: Blob | File;
    };
    path: {
        /**
         * Question ID
         */
        question_id: number;
    };
    query?: never;
    url: '/questions/{question_id}/images';
};

export type PostQuestionsByQuestionIdImagesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: unknown;
    };
};

export type PostQuestionsByQuestionIdImagesError = PostQuestionsByQuestionIdImagesErrors[keyof PostQuestionsByQuestionIdImagesErrors];

export type PostQuestionsByQuestionIdImagesResponses = {
    /**
     * Created
     */
    201: UploadUploadResponse;
};

export type PostQuestionsByQuestionIdImagesResponse = PostQuestionsByQuestionIdImagesResponses[keyof PostQuestionsByQuestionIdImagesResponses];

export type GetSubjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subjects';
};

export type GetSubjectsResponses = {
    /**
     * OK
     */
    200: Array<SubjectSubjectResponse>;
};

export type GetSubjectsResponse = GetSubjectsResponses[keyof GetSubjectsResponses];

export type GetTutoringAvailabilityData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Teacher ID (for students)
         */
        teacher_id?: number;
    };
    url: '/tutoring/availability';
};

export type GetTutoringAvailabilityResponses = {
    /**
     * OK
     */
    200: Array<TutoringAvailabilityResponse>;
};

export type GetTutoringAvailabilityResponse = GetTutoringAvailabilityResponses[keyof GetTutoringAvailabilityResponses];

export type PostTutoringAvailabilityData = {
    /**
     * Slot data
     */
    body: TutoringCreateAvailabilityInput;
    path?: never;
    query?: never;
    url: '/tutoring/availability';
};

export type PostTutoringAvailabilityErrors = {
    /**
     * Bad Request
     */
    400: TutoringErrorResponse;
};

export type PostTutoringAvailabilityError = PostTutoringAvailabilityErrors[keyof PostTutoringAvailabilityErrors];

export type PostTutoringAvailabilityResponses = {
    /**
     * Created
     */
    201: TutoringAvailabilityResponse;
};

export type PostTutoringAvailabilityResponse = PostTutoringAvailabilityResponses[keyof PostTutoringAvailabilityResponses];

export type DeleteTutoringAvailabilityByIdData = {
    body?: never;
    path: {
        /**
         * Slot ID
         */
        id: number;
    };
    query?: never;
    url: '/tutoring/availability/{id}';
};

export type DeleteTutoringAvailabilityByIdResponses = {
    /**
     * OK
     */
    200: TutoringMessageResponse;
};

export type DeleteTutoringAvailabilityByIdResponse = DeleteTutoringAvailabilityByIdResponses[keyof DeleteTutoringAvailabilityByIdResponses];

export type GetTutoringBookingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tutoring/bookings';
};

export type GetTutoringBookingsResponses = {
    /**
     * OK
     */
    200: Array<TutoringBookingResponse>;
};

export type GetTutoringBookingsResponse = GetTutoringBookingsResponses[keyof GetTutoringBookingsResponses];

export type PostTutoringBookingsData = {
    /**
     * Booking data
     */
    body: TutoringCreateBookingInput;
    path?: never;
    query?: never;
    url: '/tutoring/bookings';
};

export type PostTutoringBookingsErrors = {
    /**
     * Bad Request
     */
    400: TutoringErrorResponse;
};

export type PostTutoringBookingsError = PostTutoringBookingsErrors[keyof PostTutoringBookingsErrors];

export type PostTutoringBookingsResponses = {
    /**
     * Created
     */
    201: TutoringBookingResponse;
};

export type PostTutoringBookingsResponse = PostTutoringBookingsResponses[keyof PostTutoringBookingsResponses];

export type PatchTutoringBookingsByIdData = {
    /**
     * Status baru
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Booking ID
         */
        id: number;
    };
    query?: never;
    url: '/tutoring/bookings/{id}';
};

export type PatchTutoringBookingsByIdErrors = {
    /**
     * Bad Request
     */
    400: TutoringErrorResponse;
};

export type PatchTutoringBookingsByIdError = PatchTutoringBookingsByIdErrors[keyof PatchTutoringBookingsByIdErrors];

export type PatchTutoringBookingsByIdResponses = {
    /**
     * OK
     */
    200: TutoringBookingResponse;
};

export type PatchTutoringBookingsByIdResponse = PatchTutoringBookingsByIdResponses[keyof PatchTutoringBookingsByIdResponses];

export type GetTutoringTeachersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tutoring/teachers';
};

export type GetTutoringTeachersResponses = {
    /**
     * OK
     */
    200: Array<TutoringTeacherResponse>;
};

export type GetTutoringTeachersResponse = GetTutoringTeachersResponses[keyof GetTutoringTeachersResponses];
