// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | (string & {});
};

export type ClassClassResponse = {
    description?: string;
    id?: number;
    name?: string;
    slug?: string;
};

export type ClassErrorResponse = {
    error?: string;
};

export type ClassMessageResponse = {
    message?: string;
};

export type MaterialCreateInput = {
    content?: string;
    description?: string;
    order?: number;
    status?: string;
    subject_id?: number;
    title?: string;
};

export type MaterialErrorResponse = {
    error?: string;
};

export type MaterialMaterialResponse = {
    content?: string;
    description?: string;
    id?: number;
    order?: number;
    slug?: string;
    status?: string;
    subject_id?: number;
    subject_name?: string;
    title?: string;
};

export type MaterialMessageResponse = {
    message?: string;
};

export type MaterialUpdateInput = {
    content?: string;
    description?: string;
    order?: number;
    status?: string;
    title?: string;
};

export type SubjectCreateInput = {
    class_ids?: Array<number>;
    description?: string;
    name?: string;
};

export type SubjectErrorResponse = {
    error?: string;
};

export type SubjectMessageResponse = {
    message?: string;
};

export type SubjectSubjectResponse = {
    class_ids?: Array<number>;
    description?: string;
    id?: number;
    material_count?: number;
    name?: string;
    slug?: string;
};

export type SubjectUpdateInput = {
    class_ids?: Array<number>;
    description?: string;
    name?: string;
};

export type UserAdminUserResponse = {
    created_at?: string;
    email?: string;
    id?: number;
    name?: string;
    role?: string;
};

export type UserAuthResponse = {
    token?: string;
    user?: UserUserResponse;
};

export type UserErrorResponse = {
    error?: string;
};

export type UserLoginInput = {
    email: string;
    password: string;
};

export type UserMessageResponse = {
    message?: string;
};

export type UserRegisterInput = {
    confirm_password: string;
    email: string;
    name: string;
    password: string;
    role: 'student' | 'teacher';
};

export type UserUserResponse = {
    email?: string;
    id?: number;
    name?: string;
    role?: string;
};

export type GetAdminClassesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/classes';
};

export type GetAdminClassesResponses = {
    /**
     * OK
     */
    200: Array<ClassClassResponse>;
};

export type GetAdminClassesResponse = GetAdminClassesResponses[keyof GetAdminClassesResponses];

export type PostAdminClassesData = {
    /**
     * Data kelas
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/admin/classes';
};

export type PostAdminClassesErrors = {
    /**
     * Bad Request
     */
    400: ClassErrorResponse;
};

export type PostAdminClassesError = PostAdminClassesErrors[keyof PostAdminClassesErrors];

export type PostAdminClassesResponses = {
    /**
     * Created
     */
    201: ClassClassResponse;
};

export type PostAdminClassesResponse = PostAdminClassesResponses[keyof PostAdminClassesResponses];

export type DeleteAdminClassesByIdData = {
    body?: never;
    path: {
        /**
         * Class ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/classes/{id}';
};

export type DeleteAdminClassesByIdResponses = {
    /**
     * OK
     */
    200: ClassMessageResponse;
};

export type DeleteAdminClassesByIdResponse = DeleteAdminClassesByIdResponses[keyof DeleteAdminClassesByIdResponses];

export type PatchAdminClassesByIdData = {
    /**
     * Data update
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Class ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/classes/{id}';
};

export type PatchAdminClassesByIdErrors = {
    /**
     * Bad Request
     */
    400: ClassErrorResponse;
};

export type PatchAdminClassesByIdError = PatchAdminClassesByIdErrors[keyof PatchAdminClassesByIdErrors];

export type PatchAdminClassesByIdResponses = {
    /**
     * OK
     */
    200: ClassClassResponse;
};

export type PatchAdminClassesByIdResponse = PatchAdminClassesByIdResponses[keyof PatchAdminClassesByIdResponses];

export type GetAdminMaterialsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by subject ID
         */
        subject_id?: number;
    };
    url: '/admin/materials';
};

export type GetAdminMaterialsResponses = {
    /**
     * OK
     */
    200: Array<MaterialMaterialResponse>;
};

export type GetAdminMaterialsResponse = GetAdminMaterialsResponses[keyof GetAdminMaterialsResponses];

export type PostAdminMaterialsData = {
    /**
     * Data materi
     */
    body: MaterialCreateInput;
    path?: never;
    query?: never;
    url: '/admin/materials';
};

export type PostAdminMaterialsErrors = {
    /**
     * Bad Request
     */
    400: MaterialErrorResponse;
};

export type PostAdminMaterialsError = PostAdminMaterialsErrors[keyof PostAdminMaterialsErrors];

export type PostAdminMaterialsResponses = {
    /**
     * Created
     */
    201: MaterialMaterialResponse;
};

export type PostAdminMaterialsResponse = PostAdminMaterialsResponses[keyof PostAdminMaterialsResponses];

export type DeleteAdminMaterialsByIdData = {
    body?: never;
    path: {
        /**
         * Material ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/materials/{id}';
};

export type DeleteAdminMaterialsByIdResponses = {
    /**
     * OK
     */
    200: MaterialMessageResponse;
};

export type DeleteAdminMaterialsByIdResponse = DeleteAdminMaterialsByIdResponses[keyof DeleteAdminMaterialsByIdResponses];

export type GetAdminMaterialsByIdData = {
    body?: never;
    path: {
        /**
         * Material ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/materials/{id}';
};

export type GetAdminMaterialsByIdErrors = {
    /**
     * Not Found
     */
    404: MaterialErrorResponse;
};

export type GetAdminMaterialsByIdError = GetAdminMaterialsByIdErrors[keyof GetAdminMaterialsByIdErrors];

export type GetAdminMaterialsByIdResponses = {
    /**
     * OK
     */
    200: MaterialMaterialResponse;
};

export type GetAdminMaterialsByIdResponse = GetAdminMaterialsByIdResponses[keyof GetAdminMaterialsByIdResponses];

export type PatchAdminMaterialsByIdData = {
    /**
     * Data update
     */
    body: MaterialUpdateInput;
    path: {
        /**
         * Material ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/materials/{id}';
};

export type PatchAdminMaterialsByIdErrors = {
    /**
     * Bad Request
     */
    400: MaterialErrorResponse;
};

export type PatchAdminMaterialsByIdError = PatchAdminMaterialsByIdErrors[keyof PatchAdminMaterialsByIdErrors];

export type PatchAdminMaterialsByIdResponses = {
    /**
     * OK
     */
    200: MaterialMaterialResponse;
};

export type PatchAdminMaterialsByIdResponse = PatchAdminMaterialsByIdResponses[keyof PatchAdminMaterialsByIdResponses];

export type PostAdminSubjectsData = {
    /**
     * Data subject
     */
    body: SubjectCreateInput;
    path?: never;
    query?: never;
    url: '/admin/subjects';
};

export type PostAdminSubjectsErrors = {
    /**
     * Bad Request
     */
    400: SubjectErrorResponse;
};

export type PostAdminSubjectsError = PostAdminSubjectsErrors[keyof PostAdminSubjectsErrors];

export type PostAdminSubjectsResponses = {
    /**
     * Created
     */
    201: SubjectSubjectResponse;
};

export type PostAdminSubjectsResponse = PostAdminSubjectsResponses[keyof PostAdminSubjectsResponses];

export type DeleteAdminSubjectsByIdData = {
    body?: never;
    path: {
        /**
         * Subject ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/subjects/{id}';
};

export type DeleteAdminSubjectsByIdResponses = {
    /**
     * OK
     */
    200: SubjectMessageResponse;
};

export type DeleteAdminSubjectsByIdResponse = DeleteAdminSubjectsByIdResponses[keyof DeleteAdminSubjectsByIdResponses];

export type PatchAdminSubjectsByIdData = {
    /**
     * Data update
     */
    body: SubjectUpdateInput;
    path: {
        /**
         * Subject ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/subjects/{id}';
};

export type PatchAdminSubjectsByIdErrors = {
    /**
     * Bad Request
     */
    400: SubjectErrorResponse;
};

export type PatchAdminSubjectsByIdError = PatchAdminSubjectsByIdErrors[keyof PatchAdminSubjectsByIdErrors];

export type PatchAdminSubjectsByIdResponses = {
    /**
     * OK
     */
    200: SubjectSubjectResponse;
};

export type PatchAdminSubjectsByIdResponse = PatchAdminSubjectsByIdResponses[keyof PatchAdminSubjectsByIdResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type GetAdminUsersErrors = {
    /**
     * Internal Server Error
     */
    500: UserErrorResponse;
};

export type GetAdminUsersError = GetAdminUsersErrors[keyof GetAdminUsersErrors];

export type GetAdminUsersResponses = {
    /**
     * OK
     */
    200: Array<UserAdminUserResponse>;
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type DeleteAdminUsersByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type DeleteAdminUsersByIdErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
    /**
     * Internal Server Error
     */
    500: UserErrorResponse;
};

export type DeleteAdminUsersByIdError = DeleteAdminUsersByIdErrors[keyof DeleteAdminUsersByIdErrors];

export type DeleteAdminUsersByIdResponses = {
    /**
     * OK
     */
    200: UserMessageResponse;
};

export type DeleteAdminUsersByIdResponse = DeleteAdminUsersByIdResponses[keyof DeleteAdminUsersByIdResponses];

export type PatchAdminUsersByIdRoleData = {
    /**
     * Role baru
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}/role';
};

export type PatchAdminUsersByIdRoleErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
    /**
     * Internal Server Error
     */
    500: UserErrorResponse;
};

export type PatchAdminUsersByIdRoleError = PatchAdminUsersByIdRoleErrors[keyof PatchAdminUsersByIdRoleErrors];

export type PatchAdminUsersByIdRoleResponses = {
    /**
     * OK
     */
    200: UserMessageResponse;
};

export type PatchAdminUsersByIdRoleResponse = PatchAdminUsersByIdRoleResponses[keyof PatchAdminUsersByIdRoleResponses];

export type PostLoginData = {
    /**
     * Data login
     */
    body: UserLoginInput;
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginErrors = {
    /**
     * Unauthorized
     */
    401: UserErrorResponse;
};

export type PostLoginError = PostLoginErrors[keyof PostLoginErrors];

export type PostLoginResponses = {
    /**
     * OK
     */
    200: UserAuthResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
};

export type PostLogoutError = PostLogoutErrors[keyof PostLogoutErrors];

export type PostLogoutResponses = {
    /**
     * OK
     */
    200: UserMessageResponse;
};

export type PostLogoutResponse = PostLogoutResponses[keyof PostLogoutResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetMeErrors = {
    /**
     * Unauthorized
     */
    401: UserErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: UserUserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type PostRegisterData = {
    /**
     * Data registrasi
     */
    body: UserRegisterInput;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad Request
     */
    400: UserErrorResponse;
    /**
     * Internal Server Error
     */
    500: UserErrorResponse;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    /**
     * Created
     */
    201: UserAuthResponse;
};

export type PostRegisterResponse = PostRegisterResponses[keyof PostRegisterResponses];

export type GetSubjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subjects';
};

export type GetSubjectsResponses = {
    /**
     * OK
     */
    200: Array<SubjectSubjectResponse>;
};

export type GetSubjectsResponse = GetSubjectsResponses[keyof GetSubjectsResponses];
