generatorName: dart-dio
inputSpec: api/swagger.json
output: packages/pahamin_api
additionalProperties:
  pubName: pahamin_api
  serializationLibrary: json_serializable
  skipCopyWith: true
  useEnumExtension: false
  allowUnicodeIdentifiers: true