name: pahamin_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  dio: ^5.11.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^11.0.0
  flutter_web_auth_2: ^5.1.0
  go_router: ^17.5.0
  pahamin_api:
    path: packages/pahamin_api
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
