// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getMe, type Options, postLogin, postLogout, postRegister } from '../sdk.gen';
import type { GetMeData, GetMeError, GetMeResponse, PostLoginData, PostLoginError, PostLoginResponse, PostLogoutData, PostLogoutError, PostLogoutResponse, PostRegisterData, PostRegisterError, PostRegisterResponse } from '../types.gen';

/**
 * Login user
 *
 * Login dengan email dan password, mengembalikan token session
 */
export const postLoginMutation = (options?: Partial<Options<PostLoginData>>): UseMutationOptions<PostLoginResponse, PostLoginError, Options<PostLoginData>> => {
    const mutationOptions: UseMutationOptions<PostLoginResponse, PostLoginError, Options<PostLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout user
 *
 * Menghapus session token dari database
 */
export const postLogoutMutation = (options?: Partial<Options<PostLogoutData>>): UseMutationOptions<PostLogoutResponse, PostLogoutError, Options<PostLogoutData>> => {
    const mutationOptions: UseMutationOptions<PostLogoutResponse, PostLogoutError, Options<PostLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getMeQueryKey = (options?: Options<GetMeData>) => createQueryKey('getMe', options);

/**
 * Current user
 *
 * Mengembalikan data user berdasarkan token session
 */
export const getMeOptions = (options?: Options<GetMeData>) => queryOptions<GetMeResponse, GetMeError, GetMeResponse, ReturnType<typeof getMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMeQueryKey(options)
});

/**
 * Register user
 *
 * Mendaftarkan akun baru sebagai murid atau guru
 */
export const postRegisterMutation = (options?: Partial<Options<PostRegisterData>>): UseMutationOptions<PostRegisterResponse, PostRegisterError, Options<PostRegisterData>> => {
    const mutationOptions: UseMutationOptions<PostRegisterResponse, PostRegisterError, Options<PostRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
