// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteAdminClassesById, deleteAdminMaterialsById, deleteAdminSubjectsById, deleteAdminUsersById, getAdminClasses, getAdminMaterials, getAdminMaterialsById, getAdminUsers, getMe, getSubjects, type Options, patchAdminClassesById, patchAdminMaterialsById, patchAdminSubjectsById, patchAdminUsersByIdRole, postAdminClasses, postAdminMaterials, postAdminSubjects, postLogin, postLogout, postRegister } from '../sdk.gen';
import type { DeleteAdminClassesByIdData, DeleteAdminClassesByIdResponse, DeleteAdminMaterialsByIdData, DeleteAdminMaterialsByIdResponse, DeleteAdminSubjectsByIdData, DeleteAdminSubjectsByIdResponse, DeleteAdminUsersByIdData, DeleteAdminUsersByIdError, DeleteAdminUsersByIdResponse, GetAdminClassesData, GetAdminClassesResponse, GetAdminMaterialsByIdData, GetAdminMaterialsByIdError, GetAdminMaterialsByIdResponse, GetAdminMaterialsData, GetAdminMaterialsResponse, GetAdminUsersData, GetAdminUsersError, GetAdminUsersResponse, GetMeData, GetMeError, GetMeResponse, GetSubjectsData, GetSubjectsResponse, PatchAdminClassesByIdData, PatchAdminClassesByIdError, PatchAdminClassesByIdResponse, PatchAdminMaterialsByIdData, PatchAdminMaterialsByIdError, PatchAdminMaterialsByIdResponse, PatchAdminSubjectsByIdData, PatchAdminSubjectsByIdError, PatchAdminSubjectsByIdResponse, PatchAdminUsersByIdRoleData, PatchAdminUsersByIdRoleError, PatchAdminUsersByIdRoleResponse, PostAdminClassesData, PostAdminClassesError, PostAdminClassesResponse, PostAdminMaterialsData, PostAdminMaterialsError, PostAdminMaterialsResponse, PostAdminSubjectsData, PostAdminSubjectsError, PostAdminSubjectsResponse, PostLoginData, PostLoginError, PostLoginResponse, PostLogoutData, PostLogoutError, PostLogoutResponse, PostRegisterData, PostRegisterError, PostRegisterResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAdminClassesQueryKey = (options?: Options<GetAdminClassesData>) => createQueryKey('getAdminClasses', options);

/**
 * List classes
 *
 * Mengembalikan daftar semua kelas
 */
export const getAdminClassesOptions = (options?: Options<GetAdminClassesData>) => queryOptions<GetAdminClassesResponse, DefaultError, GetAdminClassesResponse, ReturnType<typeof getAdminClassesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAdminClasses({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAdminClassesQueryKey(options)
});

/**
 * Create class
 *
 * Menambah kelas baru
 */
export const postAdminClassesMutation = (options?: Partial<Options<PostAdminClassesData>>): UseMutationOptions<PostAdminClassesResponse, PostAdminClassesError, Options<PostAdminClassesData>> => {
    const mutationOptions: UseMutationOptions<PostAdminClassesResponse, PostAdminClassesError, Options<PostAdminClassesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAdminClasses({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete class
 *
 * Menghapus kelas
 */
export const deleteAdminClassesByIdMutation = (options?: Partial<Options<DeleteAdminClassesByIdData>>): UseMutationOptions<DeleteAdminClassesByIdResponse, DefaultError, Options<DeleteAdminClassesByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteAdminClassesByIdResponse, DefaultError, Options<DeleteAdminClassesByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAdminClassesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update class
 *
 * Mengubah kelas
 */
export const patchAdminClassesByIdMutation = (options?: Partial<Options<PatchAdminClassesByIdData>>): UseMutationOptions<PatchAdminClassesByIdResponse, PatchAdminClassesByIdError, Options<PatchAdminClassesByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchAdminClassesByIdResponse, PatchAdminClassesByIdError, Options<PatchAdminClassesByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchAdminClassesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAdminMaterialsQueryKey = (options?: Options<GetAdminMaterialsData>) => createQueryKey('getAdminMaterials', options);

/**
 * List materials
 *
 * Mengembalikan daftar semua materi, bisa difilter dengan subject_id
 */
export const getAdminMaterialsOptions = (options?: Options<GetAdminMaterialsData>) => queryOptions<GetAdminMaterialsResponse, DefaultError, GetAdminMaterialsResponse, ReturnType<typeof getAdminMaterialsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAdminMaterials({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAdminMaterialsQueryKey(options)
});

/**
 * Create material
 *
 * Menambah materi baru
 */
export const postAdminMaterialsMutation = (options?: Partial<Options<PostAdminMaterialsData>>): UseMutationOptions<PostAdminMaterialsResponse, PostAdminMaterialsError, Options<PostAdminMaterialsData>> => {
    const mutationOptions: UseMutationOptions<PostAdminMaterialsResponse, PostAdminMaterialsError, Options<PostAdminMaterialsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAdminMaterials({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete material
 *
 * Menghapus materi berdasarkan ID
 */
export const deleteAdminMaterialsByIdMutation = (options?: Partial<Options<DeleteAdminMaterialsByIdData>>): UseMutationOptions<DeleteAdminMaterialsByIdResponse, DefaultError, Options<DeleteAdminMaterialsByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteAdminMaterialsByIdResponse, DefaultError, Options<DeleteAdminMaterialsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAdminMaterialsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAdminMaterialsByIdQueryKey = (options: Options<GetAdminMaterialsByIdData>) => createQueryKey('getAdminMaterialsById', options);

/**
 * Get material
 *
 * Mengambil detail materi berdasarkan ID
 */
export const getAdminMaterialsByIdOptions = (options: Options<GetAdminMaterialsByIdData>) => queryOptions<GetAdminMaterialsByIdResponse, GetAdminMaterialsByIdError, GetAdminMaterialsByIdResponse, ReturnType<typeof getAdminMaterialsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAdminMaterialsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAdminMaterialsByIdQueryKey(options)
});

/**
 * Update material
 *
 * Mengubah materi berdasarkan ID
 */
export const patchAdminMaterialsByIdMutation = (options?: Partial<Options<PatchAdminMaterialsByIdData>>): UseMutationOptions<PatchAdminMaterialsByIdResponse, PatchAdminMaterialsByIdError, Options<PatchAdminMaterialsByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchAdminMaterialsByIdResponse, PatchAdminMaterialsByIdError, Options<PatchAdminMaterialsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchAdminMaterialsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create subject
 *
 * Menambah mata pelajaran baru (admin only)
 */
export const postAdminSubjectsMutation = (options?: Partial<Options<PostAdminSubjectsData>>): UseMutationOptions<PostAdminSubjectsResponse, PostAdminSubjectsError, Options<PostAdminSubjectsData>> => {
    const mutationOptions: UseMutationOptions<PostAdminSubjectsResponse, PostAdminSubjectsError, Options<PostAdminSubjectsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAdminSubjects({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete subject
 *
 * Menghapus mata pelajaran (admin only)
 */
export const deleteAdminSubjectsByIdMutation = (options?: Partial<Options<DeleteAdminSubjectsByIdData>>): UseMutationOptions<DeleteAdminSubjectsByIdResponse, DefaultError, Options<DeleteAdminSubjectsByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteAdminSubjectsByIdResponse, DefaultError, Options<DeleteAdminSubjectsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAdminSubjectsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update subject
 *
 * Mengubah mata pelajaran (admin only)
 */
export const patchAdminSubjectsByIdMutation = (options?: Partial<Options<PatchAdminSubjectsByIdData>>): UseMutationOptions<PatchAdminSubjectsByIdResponse, PatchAdminSubjectsByIdError, Options<PatchAdminSubjectsByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchAdminSubjectsByIdResponse, PatchAdminSubjectsByIdError, Options<PatchAdminSubjectsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchAdminSubjectsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAdminUsersQueryKey = (options?: Options<GetAdminUsersData>) => createQueryKey('getAdminUsers', options);

/**
 * List all users
 *
 * Mengembalikan daftar semua user (admin only)
 */
export const getAdminUsersOptions = (options?: Options<GetAdminUsersData>) => queryOptions<GetAdminUsersResponse, GetAdminUsersError, GetAdminUsersResponse, ReturnType<typeof getAdminUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAdminUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAdminUsersQueryKey(options)
});

/**
 * Delete user
 *
 * Menghapus user berdasarkan ID (admin only)
 */
export const deleteAdminUsersByIdMutation = (options?: Partial<Options<DeleteAdminUsersByIdData>>): UseMutationOptions<DeleteAdminUsersByIdResponse, DeleteAdminUsersByIdError, Options<DeleteAdminUsersByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteAdminUsersByIdResponse, DeleteAdminUsersByIdError, Options<DeleteAdminUsersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAdminUsersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update user role
 *
 * Mengubah role user (admin only)
 */
export const patchAdminUsersByIdRoleMutation = (options?: Partial<Options<PatchAdminUsersByIdRoleData>>): UseMutationOptions<PatchAdminUsersByIdRoleResponse, PatchAdminUsersByIdRoleError, Options<PatchAdminUsersByIdRoleData>> => {
    const mutationOptions: UseMutationOptions<PatchAdminUsersByIdRoleResponse, PatchAdminUsersByIdRoleError, Options<PatchAdminUsersByIdRoleData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchAdminUsersByIdRole({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login user
 *
 * Login dengan email dan password, mengembalikan token session
 */
export const postLoginMutation = (options?: Partial<Options<PostLoginData>>): UseMutationOptions<PostLoginResponse, PostLoginError, Options<PostLoginData>> => {
    const mutationOptions: UseMutationOptions<PostLoginResponse, PostLoginError, Options<PostLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout user
 *
 * Menghapus session token dari database
 */
export const postLogoutMutation = (options?: Partial<Options<PostLogoutData>>): UseMutationOptions<PostLogoutResponse, PostLogoutError, Options<PostLogoutData>> => {
    const mutationOptions: UseMutationOptions<PostLogoutResponse, PostLogoutError, Options<PostLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMeQueryKey = (options?: Options<GetMeData>) => createQueryKey('getMe', options);

/**
 * Current user
 *
 * Mengembalikan data user berdasarkan token session
 */
export const getMeOptions = (options?: Options<GetMeData>) => queryOptions<GetMeResponse, GetMeError, GetMeResponse, ReturnType<typeof getMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMeQueryKey(options)
});

/**
 * Register user
 *
 * Mendaftarkan akun baru sebagai murid atau guru
 */
export const postRegisterMutation = (options?: Partial<Options<PostRegisterData>>): UseMutationOptions<PostRegisterResponse, PostRegisterError, Options<PostRegisterData>> => {
    const mutationOptions: UseMutationOptions<PostRegisterResponse, PostRegisterError, Options<PostRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSubjectsQueryKey = (options?: Options<GetSubjectsData>) => createQueryKey('getSubjects', options);

/**
 * List subjects
 *
 * Mengembalikan daftar semua mata pelajaran
 */
export const getSubjectsOptions = (options?: Options<GetSubjectsData>) => queryOptions<GetSubjectsResponse, DefaultError, GetSubjectsResponse, ReturnType<typeof getSubjectsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSubjects({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSubjectsQueryKey(options)
});
