/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardMaterialsIndexRouteImport } from './routes/_dashboard.materials/index'
import { Route as DashboardForumIndexRouteImport } from './routes/_dashboard.forum/index'
import { Route as DashboardForumNewRouteImport } from './routes/_dashboard.forum/new'
import { Route as DashboardAdminUsersRouteImport } from './routes/_dashboard.admin.users'
import { Route as DashboardAdminSubjectsRouteImport } from './routes/_dashboard.admin.subjects'
import { Route as DashboardAdminClassesRouteImport } from './routes/_dashboard.admin.classes'
import { Route as DashboardAdminChaptersRouteImport } from './routes/_dashboard.admin.chapters'
import { Route as DashboardAdminMaterialsIndexRouteImport } from './routes/_dashboard.admin.materials/index'
import { Route as DashboardMaterialsChaptersIdRouteImport } from './routes/_dashboard.materials/chapters/$id'
import { Route as DashboardAdminMaterialsNewRouteImport } from './routes/_dashboard.admin.materials/new'
import { Route as DashboardMaterialsChaptersChapterIdMaterialIdRouteImport } from './routes/_dashboard.materials/chapters/$chapterId/$materialId'
import { Route as DashboardAdminMaterialsIdEditRouteImport } from './routes/_dashboard.admin.materials/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaterialsIndexRoute = DashboardMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForumIndexRoute = DashboardForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForumNewRoute = DashboardForumNewRouteImport.update({
  id: '/forum/new',
  path: '/forum/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSubjectsRoute = DashboardAdminSubjectsRouteImport.update({
  id: '/admin/subjects',
  path: '/admin/subjects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminClassesRoute = DashboardAdminClassesRouteImport.update({
  id: '/admin/classes',
  path: '/admin/classes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminChaptersRoute = DashboardAdminChaptersRouteImport.update({
  id: '/admin/chapters',
  path: '/admin/chapters',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminMaterialsIndexRoute =
  DashboardAdminMaterialsIndexRouteImport.update({
    id: '/admin/materials/',
    path: '/admin/materials/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMaterialsChaptersIdRoute =
  DashboardMaterialsChaptersIdRouteImport.update({
    id: '/materials/chapters/$id',
    path: '/materials/chapters/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminMaterialsNewRoute =
  DashboardAdminMaterialsNewRouteImport.update({
    id: '/admin/materials/new',
    path: '/admin/materials/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMaterialsChaptersChapterIdMaterialIdRoute =
  DashboardMaterialsChaptersChapterIdMaterialIdRouteImport.update({
    id: '/materials/chapters/$chapterId/$materialId',
    path: '/materials/chapters/$chapterId/$materialId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminMaterialsIdEditRoute =
  DashboardAdminMaterialsIdEditRouteImport.update({
    id: '/admin/materials/$id/edit',
    path: '/admin/materials/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/settings': typeof DashboardSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/chapters': typeof DashboardAdminChaptersRoute
  '/admin/classes': typeof DashboardAdminClassesRoute
  '/admin/subjects': typeof DashboardAdminSubjectsRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/forum/new': typeof DashboardForumNewRoute
  '/forum/': typeof DashboardForumIndexRoute
  '/materials/': typeof DashboardMaterialsIndexRoute
  '/admin/materials/new': typeof DashboardAdminMaterialsNewRoute
  '/materials/chapters/$id': typeof DashboardMaterialsChaptersIdRoute
  '/admin/materials/': typeof DashboardAdminMaterialsIndexRoute
  '/admin/materials/$id/edit': typeof DashboardAdminMaterialsIdEditRoute
  '/materials/chapters/$chapterId/$materialId': typeof DashboardMaterialsChaptersChapterIdMaterialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/settings': typeof DashboardSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/chapters': typeof DashboardAdminChaptersRoute
  '/admin/classes': typeof DashboardAdminClassesRoute
  '/admin/subjects': typeof DashboardAdminSubjectsRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/forum/new': typeof DashboardForumNewRoute
  '/forum': typeof DashboardForumIndexRoute
  '/materials': typeof DashboardMaterialsIndexRoute
  '/admin/materials/new': typeof DashboardAdminMaterialsNewRoute
  '/materials/chapters/$id': typeof DashboardMaterialsChaptersIdRoute
  '/admin/materials': typeof DashboardAdminMaterialsIndexRoute
  '/admin/materials/$id/edit': typeof DashboardAdminMaterialsIdEditRoute
  '/materials/chapters/$chapterId/$materialId': typeof DashboardMaterialsChaptersChapterIdMaterialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_dashboard/admin/chapters': typeof DashboardAdminChaptersRoute
  '/_dashboard/admin/classes': typeof DashboardAdminClassesRoute
  '/_dashboard/admin/subjects': typeof DashboardAdminSubjectsRoute
  '/_dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/_dashboard/forum/new': typeof DashboardForumNewRoute
  '/_dashboard/forum/': typeof DashboardForumIndexRoute
  '/_dashboard/materials/': typeof DashboardMaterialsIndexRoute
  '/_dashboard/admin/materials/new': typeof DashboardAdminMaterialsNewRoute
  '/_dashboard/materials/chapters/$id': typeof DashboardMaterialsChaptersIdRoute
  '/_dashboard/admin/materials/': typeof DashboardAdminMaterialsIndexRoute
  '/_dashboard/admin/materials/$id/edit': typeof DashboardAdminMaterialsIdEditRoute
  '/_dashboard/materials/chapters/$chapterId/$materialId': typeof DashboardMaterialsChaptersChapterIdMaterialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/auth/callback'
    | '/admin/chapters'
    | '/admin/classes'
    | '/admin/subjects'
    | '/admin/users'
    | '/forum/new'
    | '/forum/'
    | '/materials/'
    | '/admin/materials/new'
    | '/materials/chapters/$id'
    | '/admin/materials/'
    | '/admin/materials/$id/edit'
    | '/materials/chapters/$chapterId/$materialId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/auth/callback'
    | '/admin/chapters'
    | '/admin/classes'
    | '/admin/subjects'
    | '/admin/users'
    | '/forum/new'
    | '/forum'
    | '/materials'
    | '/admin/materials/new'
    | '/materials/chapters/$id'
    | '/admin/materials'
    | '/admin/materials/$id/edit'
    | '/materials/chapters/$chapterId/$materialId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/dashboard'
    | '/_dashboard/settings'
    | '/auth/callback'
    | '/_dashboard/admin/chapters'
    | '/_dashboard/admin/classes'
    | '/_dashboard/admin/subjects'
    | '/_dashboard/admin/users'
    | '/_dashboard/forum/new'
    | '/_dashboard/forum/'
    | '/_dashboard/materials/'
    | '/_dashboard/admin/materials/new'
    | '/_dashboard/materials/chapters/$id'
    | '/_dashboard/admin/materials/'
    | '/_dashboard/admin/materials/$id/edit'
    | '/_dashboard/materials/chapters/$chapterId/$materialId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/materials/': {
      id: '/_dashboard/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof DashboardMaterialsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/forum/': {
      id: '/_dashboard/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof DashboardForumIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/forum/new': {
      id: '/_dashboard/forum/new'
      path: '/forum/new'
      fullPath: '/forum/new'
      preLoaderRoute: typeof DashboardForumNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/users': {
      id: '/_dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/subjects': {
      id: '/_dashboard/admin/subjects'
      path: '/admin/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof DashboardAdminSubjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/classes': {
      id: '/_dashboard/admin/classes'
      path: '/admin/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof DashboardAdminClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/chapters': {
      id: '/_dashboard/admin/chapters'
      path: '/admin/chapters'
      fullPath: '/admin/chapters'
      preLoaderRoute: typeof DashboardAdminChaptersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/materials/': {
      id: '/_dashboard/admin/materials/'
      path: '/admin/materials'
      fullPath: '/admin/materials/'
      preLoaderRoute: typeof DashboardAdminMaterialsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/materials/chapters/$id': {
      id: '/_dashboard/materials/chapters/$id'
      path: '/materials/chapters/$id'
      fullPath: '/materials/chapters/$id'
      preLoaderRoute: typeof DashboardMaterialsChaptersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/materials/new': {
      id: '/_dashboard/admin/materials/new'
      path: '/admin/materials/new'
      fullPath: '/admin/materials/new'
      preLoaderRoute: typeof DashboardAdminMaterialsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/materials/chapters/$chapterId/$materialId': {
      id: '/_dashboard/materials/chapters/$chapterId/$materialId'
      path: '/materials/chapters/$chapterId/$materialId'
      fullPath: '/materials/chapters/$chapterId/$materialId'
      preLoaderRoute: typeof DashboardMaterialsChaptersChapterIdMaterialIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/materials/$id/edit': {
      id: '/_dashboard/admin/materials/$id/edit'
      path: '/admin/materials/$id/edit'
      fullPath: '/admin/materials/$id/edit'
      preLoaderRoute: typeof DashboardAdminMaterialsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardAdminChaptersRoute: typeof DashboardAdminChaptersRoute
  DashboardAdminClassesRoute: typeof DashboardAdminClassesRoute
  DashboardAdminSubjectsRoute: typeof DashboardAdminSubjectsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardForumNewRoute: typeof DashboardForumNewRoute
  DashboardForumIndexRoute: typeof DashboardForumIndexRoute
  DashboardMaterialsIndexRoute: typeof DashboardMaterialsIndexRoute
  DashboardAdminMaterialsNewRoute: typeof DashboardAdminMaterialsNewRoute
  DashboardMaterialsChaptersIdRoute: typeof DashboardMaterialsChaptersIdRoute
  DashboardAdminMaterialsIndexRoute: typeof DashboardAdminMaterialsIndexRoute
  DashboardAdminMaterialsIdEditRoute: typeof DashboardAdminMaterialsIdEditRoute
  DashboardMaterialsChaptersChapterIdMaterialIdRoute: typeof DashboardMaterialsChaptersChapterIdMaterialIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardAdminChaptersRoute: DashboardAdminChaptersRoute,
  DashboardAdminClassesRoute: DashboardAdminClassesRoute,
  DashboardAdminSubjectsRoute: DashboardAdminSubjectsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardForumNewRoute: DashboardForumNewRoute,
  DashboardForumIndexRoute: DashboardForumIndexRoute,
  DashboardMaterialsIndexRoute: DashboardMaterialsIndexRoute,
  DashboardAdminMaterialsNewRoute: DashboardAdminMaterialsNewRoute,
  DashboardMaterialsChaptersIdRoute: DashboardMaterialsChaptersIdRoute,
  DashboardAdminMaterialsIndexRoute: DashboardAdminMaterialsIndexRoute,
  DashboardAdminMaterialsIdEditRoute: DashboardAdminMaterialsIdEditRoute,
  DashboardMaterialsChaptersChapterIdMaterialIdRoute:
    DashboardMaterialsChaptersChapterIdMaterialIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
