/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardAdminUsersRouteImport } from './routes/_dashboard.admin.users'
import { Route as DashboardAdminSubjectsRouteImport } from './routes/_dashboard.admin.subjects'
import { Route as DashboardAdminMaterialsRouteImport } from './routes/_dashboard.admin.materials'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSubjectsRoute = DashboardAdminSubjectsRouteImport.update({
  id: '/admin/subjects',
  path: '/admin/subjects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminMaterialsRoute = DashboardAdminMaterialsRouteImport.update({
  id: '/admin/materials',
  path: '/admin/materials',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/admin/materials': typeof DashboardAdminMaterialsRoute
  '/admin/subjects': typeof DashboardAdminSubjectsRoute
  '/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/admin/materials': typeof DashboardAdminMaterialsRoute
  '/admin/subjects': typeof DashboardAdminSubjectsRoute
  '/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/admin/materials': typeof DashboardAdminMaterialsRoute
  '/_dashboard/admin/subjects': typeof DashboardAdminSubjectsRoute
  '/_dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/admin/materials'
    | '/admin/subjects'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/admin/materials'
    | '/admin/subjects'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/register'
    | '/_dashboard/dashboard'
    | '/_dashboard/admin/materials'
    | '/_dashboard/admin/subjects'
    | '/_dashboard/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/users': {
      id: '/_dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/subjects': {
      id: '/_dashboard/admin/subjects'
      path: '/admin/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof DashboardAdminSubjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/materials': {
      id: '/_dashboard/admin/materials'
      path: '/admin/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof DashboardAdminMaterialsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardAdminMaterialsRoute: typeof DashboardAdminMaterialsRoute
  DashboardAdminSubjectsRoute: typeof DashboardAdminSubjectsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardAdminMaterialsRoute: DashboardAdminMaterialsRoute,
  DashboardAdminSubjectsRoute: DashboardAdminSubjectsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
