/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardTeacherTutoringRouteImport } from './routes/_dashboard/teacher/tutoring'
import { Route as DashboardTeacherDashboardRouteImport } from './routes/_dashboard/teacher/dashboard'
import { Route as DashboardTeacherChaptersRouteImport } from './routes/_dashboard/teacher/chapters'
import { Route as DashboardStudentTutoringRouteImport } from './routes/_dashboard/student/tutoring'
import { Route as DashboardStudentPaymentsRouteImport } from './routes/_dashboard/student/payments'
import { Route as DashboardStudentDashboardRouteImport } from './routes/_dashboard/student/dashboard'
import { Route as DashboardAdminUsersRouteImport } from './routes/_dashboard/admin/users'
import { Route as DashboardAdminSubjectsRouteImport } from './routes/_dashboard/admin/subjects'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/_dashboard/admin/payments'
import { Route as DashboardAdminDashboardRouteImport } from './routes/_dashboard/admin/dashboard'
import { Route as DashboardAdminClassesRouteImport } from './routes/_dashboard/admin/classes'
import { Route as DashboardTeacherTutoringIndexRouteImport } from './routes/_dashboard/teacher/tutoring/index'
import { Route as DashboardTeacherQuestionBankIndexRouteImport } from './routes/_dashboard/teacher/question-bank/index'
import { Route as DashboardTeacherPacksIndexRouteImport } from './routes/_dashboard/teacher/packs/index'
import { Route as DashboardTeacherMaterialsIndexRouteImport } from './routes/_dashboard/teacher/materials/index'
import { Route as DashboardTeacherForumIndexRouteImport } from './routes/_dashboard/teacher/forum/index'
import { Route as DashboardStudentTutoringIndexRouteImport } from './routes/_dashboard/student/tutoring/index'
import { Route as DashboardStudentMaterialsIndexRouteImport } from './routes/_dashboard/student/materials/index'
import { Route as DashboardStudentForumIndexRouteImport } from './routes/_dashboard/student/forum/index'
import { Route as DashboardAdminPaymentsIndexRouteImport } from './routes/_dashboard/admin/payments/index'
import { Route as DashboardAdminForumIndexRouteImport } from './routes/_dashboard/admin/forum/index'
import { Route as DashboardTeacherTutoringAvailabilityRouteImport } from './routes/_dashboard/teacher/tutoring/availability'
import { Route as DashboardTeacherQuestionBankNewRouteImport } from './routes/_dashboard/teacher/question-bank/new'
import { Route as DashboardTeacherPacksNewRouteImport } from './routes/_dashboard/teacher/packs/new'
import { Route as DashboardTeacherPacksIdRouteImport } from './routes/_dashboard/teacher/packs/$id'
import { Route as DashboardTeacherMaterialsNewRouteImport } from './routes/_dashboard/teacher/materials/new'
import { Route as DashboardTeacherForumIdRouteImport } from './routes/_dashboard/teacher/forum/$id'
import { Route as DashboardStudentTutoringTeacherIdRouteImport } from './routes/_dashboard/student/tutoring/$teacherId'
import { Route as DashboardStudentForumNewRouteImport } from './routes/_dashboard/student/forum/new'
import { Route as DashboardStudentForumMineRouteImport } from './routes/_dashboard/student/forum/mine'
import { Route as DashboardStudentForumIdRouteImport } from './routes/_dashboard/student/forum/$id'
import { Route as DashboardAdminPaymentsUserIdRouteImport } from './routes/_dashboard/admin/payments/$userId'
import { Route as DashboardAdminForumIdRouteImport } from './routes/_dashboard/admin/forum/$id'
import { Route as DashboardTeacherPacksIdEditRouteImport } from './routes/_dashboard/teacher/packs/$id/edit'
import { Route as DashboardTeacherMaterialsIdEditRouteImport } from './routes/_dashboard/teacher/materials/$id/edit'
import { Route as DashboardStudentMaterialsChaptersIdRouteImport } from './routes/_dashboard/student/materials/chapters/$id'
import { Route as DashboardStudentMaterialsChaptersChapterIdMaterialIdRouteImport } from './routes/_dashboard/student/materials/chapters/$chapterId/$materialId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeacherTutoringRoute =
  DashboardTeacherTutoringRouteImport.update({
    id: '/teacher/tutoring',
    path: '/teacher/tutoring',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeacherDashboardRoute =
  DashboardTeacherDashboardRouteImport.update({
    id: '/teacher/dashboard',
    path: '/teacher/dashboard',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeacherChaptersRoute =
  DashboardTeacherChaptersRouteImport.update({
    id: '/teacher/chapters',
    path: '/teacher/chapters',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentTutoringRoute =
  DashboardStudentTutoringRouteImport.update({
    id: '/student/tutoring',
    path: '/student/tutoring',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentPaymentsRoute =
  DashboardStudentPaymentsRouteImport.update({
    id: '/student/payments',
    path: '/student/payments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentDashboardRoute =
  DashboardStudentDashboardRouteImport.update({
    id: '/student/dashboard',
    path: '/student/dashboard',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSubjectsRoute = DashboardAdminSubjectsRouteImport.update({
  id: '/admin/subjects',
  path: '/admin/subjects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminDashboardRoute = DashboardAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminClassesRoute = DashboardAdminClassesRouteImport.update({
  id: '/admin/classes',
  path: '/admin/classes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeacherTutoringIndexRoute =
  DashboardTeacherTutoringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTeacherTutoringRoute,
  } as any)
const DashboardTeacherQuestionBankIndexRoute =
  DashboardTeacherQuestionBankIndexRouteImport.update({
    id: '/teacher/question-bank/',
    path: '/teacher/question-bank/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeacherPacksIndexRoute =
  DashboardTeacherPacksIndexRouteImport.update({
    id: '/teacher/packs/',
    path: '/teacher/packs/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeacherMaterialsIndexRoute =
  DashboardTeacherMaterialsIndexRouteImport.update({
    id: '/teacher/materials/',
    path: '/teacher/materials/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeacherForumIndexRoute =
  DashboardTeacherForumIndexRouteImport.update({
    id: '/teacher/forum/',
    path: '/teacher/forum/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentTutoringIndexRoute =
  DashboardStudentTutoringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardStudentTutoringRoute,
  } as any)
const DashboardStudentMaterialsIndexRoute =
  DashboardStudentMaterialsIndexRouteImport.update({
    id: '/student/materials/',
    path: '/student/materials/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentForumIndexRoute =
  DashboardStudentForumIndexRouteImport.update({
    id: '/student/forum/',
    path: '/student/forum/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminPaymentsIndexRoute =
  DashboardAdminPaymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdminPaymentsRoute,
  } as any)
const DashboardAdminForumIndexRoute =
  DashboardAdminForumIndexRouteImport.update({
    id: '/admin/forum/',
    path: '/admin/forum/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeacherTutoringAvailabilityRoute =
  DashboardTeacherTutoringAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => DashboardTeacherTutoringRoute,
  } as any)
const DashboardTeacherQuestionBankNewRoute =
  DashboardTeacherQuestionBankNewRouteImport.update({
    id: '/teacher/question-bank/new',
    path: '/teacher/question-bank/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeacherPacksNewRoute =
  DashboardTeacherPacksNewRouteImport.update({
    id: '/teacher/packs/new',
    path: '/teacher/packs/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeacherPacksIdRoute = DashboardTeacherPacksIdRouteImport.update({
  id: '/teacher/packs/$id',
  path: '/teacher/packs/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeacherMaterialsNewRoute =
  DashboardTeacherMaterialsNewRouteImport.update({
    id: '/teacher/materials/new',
    path: '/teacher/materials/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeacherForumIdRoute = DashboardTeacherForumIdRouteImport.update({
  id: '/teacher/forum/$id',
  path: '/teacher/forum/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentTutoringTeacherIdRoute =
  DashboardStudentTutoringTeacherIdRouteImport.update({
    id: '/$teacherId',
    path: '/$teacherId',
    getParentRoute: () => DashboardStudentTutoringRoute,
  } as any)
const DashboardStudentForumNewRoute =
  DashboardStudentForumNewRouteImport.update({
    id: '/student/forum/new',
    path: '/student/forum/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentForumMineRoute =
  DashboardStudentForumMineRouteImport.update({
    id: '/student/forum/mine',
    path: '/student/forum/mine',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentForumIdRoute = DashboardStudentForumIdRouteImport.update({
  id: '/student/forum/$id',
  path: '/student/forum/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPaymentsUserIdRoute =
  DashboardAdminPaymentsUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => DashboardAdminPaymentsRoute,
  } as any)
const DashboardAdminForumIdRoute = DashboardAdminForumIdRouteImport.update({
  id: '/admin/forum/$id',
  path: '/admin/forum/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeacherPacksIdEditRoute =
  DashboardTeacherPacksIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardTeacherPacksIdRoute,
  } as any)
const DashboardTeacherMaterialsIdEditRoute =
  DashboardTeacherMaterialsIdEditRouteImport.update({
    id: '/teacher/materials/$id/edit',
    path: '/teacher/materials/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentMaterialsChaptersIdRoute =
  DashboardStudentMaterialsChaptersIdRouteImport.update({
    id: '/student/materials/chapters/$id',
    path: '/student/materials/chapters/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentMaterialsChaptersChapterIdMaterialIdRoute =
  DashboardStudentMaterialsChaptersChapterIdMaterialIdRouteImport.update({
    id: '/student/materials/chapters/$chapterId/$materialId',
    path: '/student/materials/chapters/$chapterId/$materialId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof DashboardSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/classes': typeof DashboardAdminClassesRoute
  '/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/admin/payments': typeof DashboardAdminPaymentsRouteWithChildren
  '/admin/subjects': typeof DashboardAdminSubjectsRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/student/dashboard': typeof DashboardStudentDashboardRoute
  '/student/payments': typeof DashboardStudentPaymentsRoute
  '/student/tutoring': typeof DashboardStudentTutoringRouteWithChildren
  '/teacher/chapters': typeof DashboardTeacherChaptersRoute
  '/teacher/dashboard': typeof DashboardTeacherDashboardRoute
  '/teacher/tutoring': typeof DashboardTeacherTutoringRouteWithChildren
  '/admin/forum/$id': typeof DashboardAdminForumIdRoute
  '/admin/payments/$userId': typeof DashboardAdminPaymentsUserIdRoute
  '/student/forum/$id': typeof DashboardStudentForumIdRoute
  '/student/forum/mine': typeof DashboardStudentForumMineRoute
  '/student/forum/new': typeof DashboardStudentForumNewRoute
  '/student/tutoring/$teacherId': typeof DashboardStudentTutoringTeacherIdRoute
  '/teacher/forum/$id': typeof DashboardTeacherForumIdRoute
  '/teacher/materials/new': typeof DashboardTeacherMaterialsNewRoute
  '/teacher/packs/$id': typeof DashboardTeacherPacksIdRouteWithChildren
  '/teacher/packs/new': typeof DashboardTeacherPacksNewRoute
  '/teacher/question-bank/new': typeof DashboardTeacherQuestionBankNewRoute
  '/teacher/tutoring/availability': typeof DashboardTeacherTutoringAvailabilityRoute
  '/admin/forum/': typeof DashboardAdminForumIndexRoute
  '/admin/payments/': typeof DashboardAdminPaymentsIndexRoute
  '/student/forum/': typeof DashboardStudentForumIndexRoute
  '/student/materials/': typeof DashboardStudentMaterialsIndexRoute
  '/student/tutoring/': typeof DashboardStudentTutoringIndexRoute
  '/teacher/forum/': typeof DashboardTeacherForumIndexRoute
  '/teacher/materials/': typeof DashboardTeacherMaterialsIndexRoute
  '/teacher/packs/': typeof DashboardTeacherPacksIndexRoute
  '/teacher/question-bank/': typeof DashboardTeacherQuestionBankIndexRoute
  '/teacher/tutoring/': typeof DashboardTeacherTutoringIndexRoute
  '/student/materials/chapters/$id': typeof DashboardStudentMaterialsChaptersIdRoute
  '/teacher/materials/$id/edit': typeof DashboardTeacherMaterialsIdEditRoute
  '/teacher/packs/$id/edit': typeof DashboardTeacherPacksIdEditRoute
  '/student/materials/chapters/$chapterId/$materialId': typeof DashboardStudentMaterialsChaptersChapterIdMaterialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof DashboardSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/classes': typeof DashboardAdminClassesRoute
  '/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/admin/subjects': typeof DashboardAdminSubjectsRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/student/dashboard': typeof DashboardStudentDashboardRoute
  '/student/payments': typeof DashboardStudentPaymentsRoute
  '/teacher/chapters': typeof DashboardTeacherChaptersRoute
  '/teacher/dashboard': typeof DashboardTeacherDashboardRoute
  '/admin/forum/$id': typeof DashboardAdminForumIdRoute
  '/admin/payments/$userId': typeof DashboardAdminPaymentsUserIdRoute
  '/student/forum/$id': typeof DashboardStudentForumIdRoute
  '/student/forum/mine': typeof DashboardStudentForumMineRoute
  '/student/forum/new': typeof DashboardStudentForumNewRoute
  '/student/tutoring/$teacherId': typeof DashboardStudentTutoringTeacherIdRoute
  '/teacher/forum/$id': typeof DashboardTeacherForumIdRoute
  '/teacher/materials/new': typeof DashboardTeacherMaterialsNewRoute
  '/teacher/packs/$id': typeof DashboardTeacherPacksIdRouteWithChildren
  '/teacher/packs/new': typeof DashboardTeacherPacksNewRoute
  '/teacher/question-bank/new': typeof DashboardTeacherQuestionBankNewRoute
  '/teacher/tutoring/availability': typeof DashboardTeacherTutoringAvailabilityRoute
  '/admin/forum': typeof DashboardAdminForumIndexRoute
  '/admin/payments': typeof DashboardAdminPaymentsIndexRoute
  '/student/forum': typeof DashboardStudentForumIndexRoute
  '/student/materials': typeof DashboardStudentMaterialsIndexRoute
  '/student/tutoring': typeof DashboardStudentTutoringIndexRoute
  '/teacher/forum': typeof DashboardTeacherForumIndexRoute
  '/teacher/materials': typeof DashboardTeacherMaterialsIndexRoute
  '/teacher/packs': typeof DashboardTeacherPacksIndexRoute
  '/teacher/question-bank': typeof DashboardTeacherQuestionBankIndexRoute
  '/teacher/tutoring': typeof DashboardTeacherTutoringIndexRoute
  '/student/materials/chapters/$id': typeof DashboardStudentMaterialsChaptersIdRoute
  '/teacher/materials/$id/edit': typeof DashboardTeacherMaterialsIdEditRoute
  '/teacher/packs/$id/edit': typeof DashboardTeacherPacksIdEditRoute
  '/student/materials/chapters/$chapterId/$materialId': typeof DashboardStudentMaterialsChaptersChapterIdMaterialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_dashboard/admin/classes': typeof DashboardAdminClassesRoute
  '/_dashboard/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/_dashboard/admin/payments': typeof DashboardAdminPaymentsRouteWithChildren
  '/_dashboard/admin/subjects': typeof DashboardAdminSubjectsRoute
  '/_dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/_dashboard/student/dashboard': typeof DashboardStudentDashboardRoute
  '/_dashboard/student/payments': typeof DashboardStudentPaymentsRoute
  '/_dashboard/student/tutoring': typeof DashboardStudentTutoringRouteWithChildren
  '/_dashboard/teacher/chapters': typeof DashboardTeacherChaptersRoute
  '/_dashboard/teacher/dashboard': typeof DashboardTeacherDashboardRoute
  '/_dashboard/teacher/tutoring': typeof DashboardTeacherTutoringRouteWithChildren
  '/_dashboard/admin/forum/$id': typeof DashboardAdminForumIdRoute
  '/_dashboard/admin/payments/$userId': typeof DashboardAdminPaymentsUserIdRoute
  '/_dashboard/student/forum/$id': typeof DashboardStudentForumIdRoute
  '/_dashboard/student/forum/mine': typeof DashboardStudentForumMineRoute
  '/_dashboard/student/forum/new': typeof DashboardStudentForumNewRoute
  '/_dashboard/student/tutoring/$teacherId': typeof DashboardStudentTutoringTeacherIdRoute
  '/_dashboard/teacher/forum/$id': typeof DashboardTeacherForumIdRoute
  '/_dashboard/teacher/materials/new': typeof DashboardTeacherMaterialsNewRoute
  '/_dashboard/teacher/packs/$id': typeof DashboardTeacherPacksIdRouteWithChildren
  '/_dashboard/teacher/packs/new': typeof DashboardTeacherPacksNewRoute
  '/_dashboard/teacher/question-bank/new': typeof DashboardTeacherQuestionBankNewRoute
  '/_dashboard/teacher/tutoring/availability': typeof DashboardTeacherTutoringAvailabilityRoute
  '/_dashboard/admin/forum/': typeof DashboardAdminForumIndexRoute
  '/_dashboard/admin/payments/': typeof DashboardAdminPaymentsIndexRoute
  '/_dashboard/student/forum/': typeof DashboardStudentForumIndexRoute
  '/_dashboard/student/materials/': typeof DashboardStudentMaterialsIndexRoute
  '/_dashboard/student/tutoring/': typeof DashboardStudentTutoringIndexRoute
  '/_dashboard/teacher/forum/': typeof DashboardTeacherForumIndexRoute
  '/_dashboard/teacher/materials/': typeof DashboardTeacherMaterialsIndexRoute
  '/_dashboard/teacher/packs/': typeof DashboardTeacherPacksIndexRoute
  '/_dashboard/teacher/question-bank/': typeof DashboardTeacherQuestionBankIndexRoute
  '/_dashboard/teacher/tutoring/': typeof DashboardTeacherTutoringIndexRoute
  '/_dashboard/student/materials/chapters/$id': typeof DashboardStudentMaterialsChaptersIdRoute
  '/_dashboard/teacher/materials/$id/edit': typeof DashboardTeacherMaterialsIdEditRoute
  '/_dashboard/teacher/packs/$id/edit': typeof DashboardTeacherPacksIdEditRoute
  '/_dashboard/student/materials/chapters/$chapterId/$materialId': typeof DashboardStudentMaterialsChaptersChapterIdMaterialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/auth/callback'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/admin/subjects'
    | '/admin/users'
    | '/student/dashboard'
    | '/student/payments'
    | '/student/tutoring'
    | '/teacher/chapters'
    | '/teacher/dashboard'
    | '/teacher/tutoring'
    | '/admin/forum/$id'
    | '/admin/payments/$userId'
    | '/student/forum/$id'
    | '/student/forum/mine'
    | '/student/forum/new'
    | '/student/tutoring/$teacherId'
    | '/teacher/forum/$id'
    | '/teacher/materials/new'
    | '/teacher/packs/$id'
    | '/teacher/packs/new'
    | '/teacher/question-bank/new'
    | '/teacher/tutoring/availability'
    | '/admin/forum/'
    | '/admin/payments/'
    | '/student/forum/'
    | '/student/materials/'
    | '/student/tutoring/'
    | '/teacher/forum/'
    | '/teacher/materials/'
    | '/teacher/packs/'
    | '/teacher/question-bank/'
    | '/teacher/tutoring/'
    | '/student/materials/chapters/$id'
    | '/teacher/materials/$id/edit'
    | '/teacher/packs/$id/edit'
    | '/student/materials/chapters/$chapterId/$materialId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/auth/callback'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/subjects'
    | '/admin/users'
    | '/student/dashboard'
    | '/student/payments'
    | '/teacher/chapters'
    | '/teacher/dashboard'
    | '/admin/forum/$id'
    | '/admin/payments/$userId'
    | '/student/forum/$id'
    | '/student/forum/mine'
    | '/student/forum/new'
    | '/student/tutoring/$teacherId'
    | '/teacher/forum/$id'
    | '/teacher/materials/new'
    | '/teacher/packs/$id'
    | '/teacher/packs/new'
    | '/teacher/question-bank/new'
    | '/teacher/tutoring/availability'
    | '/admin/forum'
    | '/admin/payments'
    | '/student/forum'
    | '/student/materials'
    | '/student/tutoring'
    | '/teacher/forum'
    | '/teacher/materials'
    | '/teacher/packs'
    | '/teacher/question-bank'
    | '/teacher/tutoring'
    | '/student/materials/chapters/$id'
    | '/teacher/materials/$id/edit'
    | '/teacher/packs/$id/edit'
    | '/student/materials/chapters/$chapterId/$materialId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/settings'
    | '/auth/callback'
    | '/_dashboard/admin/classes'
    | '/_dashboard/admin/dashboard'
    | '/_dashboard/admin/payments'
    | '/_dashboard/admin/subjects'
    | '/_dashboard/admin/users'
    | '/_dashboard/student/dashboard'
    | '/_dashboard/student/payments'
    | '/_dashboard/student/tutoring'
    | '/_dashboard/teacher/chapters'
    | '/_dashboard/teacher/dashboard'
    | '/_dashboard/teacher/tutoring'
    | '/_dashboard/admin/forum/$id'
    | '/_dashboard/admin/payments/$userId'
    | '/_dashboard/student/forum/$id'
    | '/_dashboard/student/forum/mine'
    | '/_dashboard/student/forum/new'
    | '/_dashboard/student/tutoring/$teacherId'
    | '/_dashboard/teacher/forum/$id'
    | '/_dashboard/teacher/materials/new'
    | '/_dashboard/teacher/packs/$id'
    | '/_dashboard/teacher/packs/new'
    | '/_dashboard/teacher/question-bank/new'
    | '/_dashboard/teacher/tutoring/availability'
    | '/_dashboard/admin/forum/'
    | '/_dashboard/admin/payments/'
    | '/_dashboard/student/forum/'
    | '/_dashboard/student/materials/'
    | '/_dashboard/student/tutoring/'
    | '/_dashboard/teacher/forum/'
    | '/_dashboard/teacher/materials/'
    | '/_dashboard/teacher/packs/'
    | '/_dashboard/teacher/question-bank/'
    | '/_dashboard/teacher/tutoring/'
    | '/_dashboard/student/materials/chapters/$id'
    | '/_dashboard/teacher/materials/$id/edit'
    | '/_dashboard/teacher/packs/$id/edit'
    | '/_dashboard/student/materials/chapters/$chapterId/$materialId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/tutoring': {
      id: '/_dashboard/teacher/tutoring'
      path: '/teacher/tutoring'
      fullPath: '/teacher/tutoring'
      preLoaderRoute: typeof DashboardTeacherTutoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/dashboard': {
      id: '/_dashboard/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof DashboardTeacherDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/chapters': {
      id: '/_dashboard/teacher/chapters'
      path: '/teacher/chapters'
      fullPath: '/teacher/chapters'
      preLoaderRoute: typeof DashboardTeacherChaptersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student/tutoring': {
      id: '/_dashboard/student/tutoring'
      path: '/student/tutoring'
      fullPath: '/student/tutoring'
      preLoaderRoute: typeof DashboardStudentTutoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student/payments': {
      id: '/_dashboard/student/payments'
      path: '/student/payments'
      fullPath: '/student/payments'
      preLoaderRoute: typeof DashboardStudentPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student/dashboard': {
      id: '/_dashboard/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof DashboardStudentDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/users': {
      id: '/_dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/subjects': {
      id: '/_dashboard/admin/subjects'
      path: '/admin/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof DashboardAdminSubjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/payments': {
      id: '/_dashboard/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/dashboard': {
      id: '/_dashboard/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof DashboardAdminDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/classes': {
      id: '/_dashboard/admin/classes'
      path: '/admin/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof DashboardAdminClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/tutoring/': {
      id: '/_dashboard/teacher/tutoring/'
      path: '/'
      fullPath: '/teacher/tutoring/'
      preLoaderRoute: typeof DashboardTeacherTutoringIndexRouteImport
      parentRoute: typeof DashboardTeacherTutoringRoute
    }
    '/_dashboard/teacher/question-bank/': {
      id: '/_dashboard/teacher/question-bank/'
      path: '/teacher/question-bank'
      fullPath: '/teacher/question-bank/'
      preLoaderRoute: typeof DashboardTeacherQuestionBankIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/packs/': {
      id: '/_dashboard/teacher/packs/'
      path: '/teacher/packs'
      fullPath: '/teacher/packs/'
      preLoaderRoute: typeof DashboardTeacherPacksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/materials/': {
      id: '/_dashboard/teacher/materials/'
      path: '/teacher/materials'
      fullPath: '/teacher/materials/'
      preLoaderRoute: typeof DashboardTeacherMaterialsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/forum/': {
      id: '/_dashboard/teacher/forum/'
      path: '/teacher/forum'
      fullPath: '/teacher/forum/'
      preLoaderRoute: typeof DashboardTeacherForumIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student/tutoring/': {
      id: '/_dashboard/student/tutoring/'
      path: '/'
      fullPath: '/student/tutoring/'
      preLoaderRoute: typeof DashboardStudentTutoringIndexRouteImport
      parentRoute: typeof DashboardStudentTutoringRoute
    }
    '/_dashboard/student/materials/': {
      id: '/_dashboard/student/materials/'
      path: '/student/materials'
      fullPath: '/student/materials/'
      preLoaderRoute: typeof DashboardStudentMaterialsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student/forum/': {
      id: '/_dashboard/student/forum/'
      path: '/student/forum'
      fullPath: '/student/forum/'
      preLoaderRoute: typeof DashboardStudentForumIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/payments/': {
      id: '/_dashboard/admin/payments/'
      path: '/'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof DashboardAdminPaymentsIndexRouteImport
      parentRoute: typeof DashboardAdminPaymentsRoute
    }
    '/_dashboard/admin/forum/': {
      id: '/_dashboard/admin/forum/'
      path: '/admin/forum'
      fullPath: '/admin/forum/'
      preLoaderRoute: typeof DashboardAdminForumIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/tutoring/availability': {
      id: '/_dashboard/teacher/tutoring/availability'
      path: '/availability'
      fullPath: '/teacher/tutoring/availability'
      preLoaderRoute: typeof DashboardTeacherTutoringAvailabilityRouteImport
      parentRoute: typeof DashboardTeacherTutoringRoute
    }
    '/_dashboard/teacher/question-bank/new': {
      id: '/_dashboard/teacher/question-bank/new'
      path: '/teacher/question-bank/new'
      fullPath: '/teacher/question-bank/new'
      preLoaderRoute: typeof DashboardTeacherQuestionBankNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/packs/new': {
      id: '/_dashboard/teacher/packs/new'
      path: '/teacher/packs/new'
      fullPath: '/teacher/packs/new'
      preLoaderRoute: typeof DashboardTeacherPacksNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/packs/$id': {
      id: '/_dashboard/teacher/packs/$id'
      path: '/teacher/packs/$id'
      fullPath: '/teacher/packs/$id'
      preLoaderRoute: typeof DashboardTeacherPacksIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/materials/new': {
      id: '/_dashboard/teacher/materials/new'
      path: '/teacher/materials/new'
      fullPath: '/teacher/materials/new'
      preLoaderRoute: typeof DashboardTeacherMaterialsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/forum/$id': {
      id: '/_dashboard/teacher/forum/$id'
      path: '/teacher/forum/$id'
      fullPath: '/teacher/forum/$id'
      preLoaderRoute: typeof DashboardTeacherForumIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student/tutoring/$teacherId': {
      id: '/_dashboard/student/tutoring/$teacherId'
      path: '/$teacherId'
      fullPath: '/student/tutoring/$teacherId'
      preLoaderRoute: typeof DashboardStudentTutoringTeacherIdRouteImport
      parentRoute: typeof DashboardStudentTutoringRoute
    }
    '/_dashboard/student/forum/new': {
      id: '/_dashboard/student/forum/new'
      path: '/student/forum/new'
      fullPath: '/student/forum/new'
      preLoaderRoute: typeof DashboardStudentForumNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student/forum/mine': {
      id: '/_dashboard/student/forum/mine'
      path: '/student/forum/mine'
      fullPath: '/student/forum/mine'
      preLoaderRoute: typeof DashboardStudentForumMineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student/forum/$id': {
      id: '/_dashboard/student/forum/$id'
      path: '/student/forum/$id'
      fullPath: '/student/forum/$id'
      preLoaderRoute: typeof DashboardStudentForumIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/payments/$userId': {
      id: '/_dashboard/admin/payments/$userId'
      path: '/$userId'
      fullPath: '/admin/payments/$userId'
      preLoaderRoute: typeof DashboardAdminPaymentsUserIdRouteImport
      parentRoute: typeof DashboardAdminPaymentsRoute
    }
    '/_dashboard/admin/forum/$id': {
      id: '/_dashboard/admin/forum/$id'
      path: '/admin/forum/$id'
      fullPath: '/admin/forum/$id'
      preLoaderRoute: typeof DashboardAdminForumIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher/packs/$id/edit': {
      id: '/_dashboard/teacher/packs/$id/edit'
      path: '/edit'
      fullPath: '/teacher/packs/$id/edit'
      preLoaderRoute: typeof DashboardTeacherPacksIdEditRouteImport
      parentRoute: typeof DashboardTeacherPacksIdRoute
    }
    '/_dashboard/teacher/materials/$id/edit': {
      id: '/_dashboard/teacher/materials/$id/edit'
      path: '/teacher/materials/$id/edit'
      fullPath: '/teacher/materials/$id/edit'
      preLoaderRoute: typeof DashboardTeacherMaterialsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student/materials/chapters/$id': {
      id: '/_dashboard/student/materials/chapters/$id'
      path: '/student/materials/chapters/$id'
      fullPath: '/student/materials/chapters/$id'
      preLoaderRoute: typeof DashboardStudentMaterialsChaptersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student/materials/chapters/$chapterId/$materialId': {
      id: '/_dashboard/student/materials/chapters/$chapterId/$materialId'
      path: '/student/materials/chapters/$chapterId/$materialId'
      fullPath: '/student/materials/chapters/$chapterId/$materialId'
      preLoaderRoute: typeof DashboardStudentMaterialsChaptersChapterIdMaterialIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardAdminPaymentsRouteChildren {
  DashboardAdminPaymentsUserIdRoute: typeof DashboardAdminPaymentsUserIdRoute
  DashboardAdminPaymentsIndexRoute: typeof DashboardAdminPaymentsIndexRoute
}

const DashboardAdminPaymentsRouteChildren: DashboardAdminPaymentsRouteChildren =
  {
    DashboardAdminPaymentsUserIdRoute: DashboardAdminPaymentsUserIdRoute,
    DashboardAdminPaymentsIndexRoute: DashboardAdminPaymentsIndexRoute,
  }

const DashboardAdminPaymentsRouteWithChildren =
  DashboardAdminPaymentsRoute._addFileChildren(
    DashboardAdminPaymentsRouteChildren,
  )

interface DashboardStudentTutoringRouteChildren {
  DashboardStudentTutoringTeacherIdRoute: typeof DashboardStudentTutoringTeacherIdRoute
  DashboardStudentTutoringIndexRoute: typeof DashboardStudentTutoringIndexRoute
}

const DashboardStudentTutoringRouteChildren: DashboardStudentTutoringRouteChildren =
  {
    DashboardStudentTutoringTeacherIdRoute:
      DashboardStudentTutoringTeacherIdRoute,
    DashboardStudentTutoringIndexRoute: DashboardStudentTutoringIndexRoute,
  }

const DashboardStudentTutoringRouteWithChildren =
  DashboardStudentTutoringRoute._addFileChildren(
    DashboardStudentTutoringRouteChildren,
  )

interface DashboardTeacherTutoringRouteChildren {
  DashboardTeacherTutoringAvailabilityRoute: typeof DashboardTeacherTutoringAvailabilityRoute
  DashboardTeacherTutoringIndexRoute: typeof DashboardTeacherTutoringIndexRoute
}

const DashboardTeacherTutoringRouteChildren: DashboardTeacherTutoringRouteChildren =
  {
    DashboardTeacherTutoringAvailabilityRoute:
      DashboardTeacherTutoringAvailabilityRoute,
    DashboardTeacherTutoringIndexRoute: DashboardTeacherTutoringIndexRoute,
  }

const DashboardTeacherTutoringRouteWithChildren =
  DashboardTeacherTutoringRoute._addFileChildren(
    DashboardTeacherTutoringRouteChildren,
  )

interface DashboardTeacherPacksIdRouteChildren {
  DashboardTeacherPacksIdEditRoute: typeof DashboardTeacherPacksIdEditRoute
}

const DashboardTeacherPacksIdRouteChildren: DashboardTeacherPacksIdRouteChildren =
  {
    DashboardTeacherPacksIdEditRoute: DashboardTeacherPacksIdEditRoute,
  }

const DashboardTeacherPacksIdRouteWithChildren =
  DashboardTeacherPacksIdRoute._addFileChildren(
    DashboardTeacherPacksIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardAdminClassesRoute: typeof DashboardAdminClassesRoute
  DashboardAdminDashboardRoute: typeof DashboardAdminDashboardRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRouteWithChildren
  DashboardAdminSubjectsRoute: typeof DashboardAdminSubjectsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardStudentDashboardRoute: typeof DashboardStudentDashboardRoute
  DashboardStudentPaymentsRoute: typeof DashboardStudentPaymentsRoute
  DashboardStudentTutoringRoute: typeof DashboardStudentTutoringRouteWithChildren
  DashboardTeacherChaptersRoute: typeof DashboardTeacherChaptersRoute
  DashboardTeacherDashboardRoute: typeof DashboardTeacherDashboardRoute
  DashboardTeacherTutoringRoute: typeof DashboardTeacherTutoringRouteWithChildren
  DashboardAdminForumIdRoute: typeof DashboardAdminForumIdRoute
  DashboardStudentForumIdRoute: typeof DashboardStudentForumIdRoute
  DashboardStudentForumMineRoute: typeof DashboardStudentForumMineRoute
  DashboardStudentForumNewRoute: typeof DashboardStudentForumNewRoute
  DashboardTeacherForumIdRoute: typeof DashboardTeacherForumIdRoute
  DashboardTeacherMaterialsNewRoute: typeof DashboardTeacherMaterialsNewRoute
  DashboardTeacherPacksIdRoute: typeof DashboardTeacherPacksIdRouteWithChildren
  DashboardTeacherPacksNewRoute: typeof DashboardTeacherPacksNewRoute
  DashboardTeacherQuestionBankNewRoute: typeof DashboardTeacherQuestionBankNewRoute
  DashboardAdminForumIndexRoute: typeof DashboardAdminForumIndexRoute
  DashboardStudentForumIndexRoute: typeof DashboardStudentForumIndexRoute
  DashboardStudentMaterialsIndexRoute: typeof DashboardStudentMaterialsIndexRoute
  DashboardTeacherForumIndexRoute: typeof DashboardTeacherForumIndexRoute
  DashboardTeacherMaterialsIndexRoute: typeof DashboardTeacherMaterialsIndexRoute
  DashboardTeacherPacksIndexRoute: typeof DashboardTeacherPacksIndexRoute
  DashboardTeacherQuestionBankIndexRoute: typeof DashboardTeacherQuestionBankIndexRoute
  DashboardStudentMaterialsChaptersIdRoute: typeof DashboardStudentMaterialsChaptersIdRoute
  DashboardTeacherMaterialsIdEditRoute: typeof DashboardTeacherMaterialsIdEditRoute
  DashboardStudentMaterialsChaptersChapterIdMaterialIdRoute: typeof DashboardStudentMaterialsChaptersChapterIdMaterialIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardAdminClassesRoute: DashboardAdminClassesRoute,
  DashboardAdminDashboardRoute: DashboardAdminDashboardRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRouteWithChildren,
  DashboardAdminSubjectsRoute: DashboardAdminSubjectsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardStudentDashboardRoute: DashboardStudentDashboardRoute,
  DashboardStudentPaymentsRoute: DashboardStudentPaymentsRoute,
  DashboardStudentTutoringRoute: DashboardStudentTutoringRouteWithChildren,
  DashboardTeacherChaptersRoute: DashboardTeacherChaptersRoute,
  DashboardTeacherDashboardRoute: DashboardTeacherDashboardRoute,
  DashboardTeacherTutoringRoute: DashboardTeacherTutoringRouteWithChildren,
  DashboardAdminForumIdRoute: DashboardAdminForumIdRoute,
  DashboardStudentForumIdRoute: DashboardStudentForumIdRoute,
  DashboardStudentForumMineRoute: DashboardStudentForumMineRoute,
  DashboardStudentForumNewRoute: DashboardStudentForumNewRoute,
  DashboardTeacherForumIdRoute: DashboardTeacherForumIdRoute,
  DashboardTeacherMaterialsNewRoute: DashboardTeacherMaterialsNewRoute,
  DashboardTeacherPacksIdRoute: DashboardTeacherPacksIdRouteWithChildren,
  DashboardTeacherPacksNewRoute: DashboardTeacherPacksNewRoute,
  DashboardTeacherQuestionBankNewRoute: DashboardTeacherQuestionBankNewRoute,
  DashboardAdminForumIndexRoute: DashboardAdminForumIndexRoute,
  DashboardStudentForumIndexRoute: DashboardStudentForumIndexRoute,
  DashboardStudentMaterialsIndexRoute: DashboardStudentMaterialsIndexRoute,
  DashboardTeacherForumIndexRoute: DashboardTeacherForumIndexRoute,
  DashboardTeacherMaterialsIndexRoute: DashboardTeacherMaterialsIndexRoute,
  DashboardTeacherPacksIndexRoute: DashboardTeacherPacksIndexRoute,
  DashboardTeacherQuestionBankIndexRoute:
    DashboardTeacherQuestionBankIndexRoute,
  DashboardStudentMaterialsChaptersIdRoute:
    DashboardStudentMaterialsChaptersIdRoute,
  DashboardTeacherMaterialsIdEditRoute: DashboardTeacherMaterialsIdEditRoute,
  DashboardStudentMaterialsChaptersChapterIdMaterialIdRoute:
    DashboardStudentMaterialsChaptersChapterIdMaterialIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
